<?php
/**
 * SxapisrgetdefaultrestockdataResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SxapisrgetdefaultrestockdataResponse Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SxapisrgetdefaultrestockdataResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'sxapisrgetdefaultrestockdata_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'restock_type' => 'string',
        'restock_amount' => 'double',
        'restock_nopo_type' => 'string',
        'restock_nopo_amount' => 'double',
        'c_error_message' => 'string',
        't_outfieldvalue' => '\Swagger\Client\Model\TOutfieldvalueResp'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'restock_type' => null,
        'restock_amount' => 'double',
        'restock_nopo_type' => null,
        'restock_nopo_amount' => 'double',
        'c_error_message' => null,
        't_outfieldvalue' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'restock_type' => 'restockType',
        'restock_amount' => 'restockAmount',
        'restock_nopo_type' => 'restockNOPOType',
        'restock_nopo_amount' => 'restockNOPOAmount',
        'c_error_message' => 'cErrorMessage',
        't_outfieldvalue' => 'tOutfieldvalue'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'restock_type' => 'setRestockType',
        'restock_amount' => 'setRestockAmount',
        'restock_nopo_type' => 'setRestockNopoType',
        'restock_nopo_amount' => 'setRestockNopoAmount',
        'c_error_message' => 'setCErrorMessage',
        't_outfieldvalue' => 'setTOutfieldvalue'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'restock_type' => 'getRestockType',
        'restock_amount' => 'getRestockAmount',
        'restock_nopo_type' => 'getRestockNopoType',
        'restock_nopo_amount' => 'getRestockNopoAmount',
        'c_error_message' => 'getCErrorMessage',
        't_outfieldvalue' => 'getTOutfieldvalue'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['restock_type'] = isset($data['restock_type']) ? $data['restock_type'] : null;
        $this->container['restock_amount'] = isset($data['restock_amount']) ? $data['restock_amount'] : null;
        $this->container['restock_nopo_type'] = isset($data['restock_nopo_type']) ? $data['restock_nopo_type'] : null;
        $this->container['restock_nopo_amount'] = isset($data['restock_nopo_amount']) ? $data['restock_nopo_amount'] : null;
        $this->container['c_error_message'] = isset($data['c_error_message']) ? $data['c_error_message'] : null;
        $this->container['t_outfieldvalue'] = isset($data['t_outfieldvalue']) ? $data['t_outfieldvalue'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets restock_type
     *
     * @return string
     */
    public function getRestockType()
    {
        return $this->container['restock_type'];
    }

    /**
     * Sets restock_type
     *
     * @param string $restock_type restock_type
     *
     * @return $this
     */
    public function setRestockType($restock_type)
    {
        $this->container['restock_type'] = $restock_type;

        return $this;
    }

    /**
     * Gets restock_amount
     *
     * @return double
     */
    public function getRestockAmount()
    {
        return $this->container['restock_amount'];
    }

    /**
     * Sets restock_amount
     *
     * @param double $restock_amount restock_amount
     *
     * @return $this
     */
    public function setRestockAmount($restock_amount)
    {
        $this->container['restock_amount'] = $restock_amount;

        return $this;
    }

    /**
     * Gets restock_nopo_type
     *
     * @return string
     */
    public function getRestockNopoType()
    {
        return $this->container['restock_nopo_type'];
    }

    /**
     * Sets restock_nopo_type
     *
     * @param string $restock_nopo_type restock_nopo_type
     *
     * @return $this
     */
    public function setRestockNopoType($restock_nopo_type)
    {
        $this->container['restock_nopo_type'] = $restock_nopo_type;

        return $this;
    }

    /**
     * Gets restock_nopo_amount
     *
     * @return double
     */
    public function getRestockNopoAmount()
    {
        return $this->container['restock_nopo_amount'];
    }

    /**
     * Sets restock_nopo_amount
     *
     * @param double $restock_nopo_amount restock_nopo_amount
     *
     * @return $this
     */
    public function setRestockNopoAmount($restock_nopo_amount)
    {
        $this->container['restock_nopo_amount'] = $restock_nopo_amount;

        return $this;
    }

    /**
     * Gets c_error_message
     *
     * @return string
     */
    public function getCErrorMessage()
    {
        return $this->container['c_error_message'];
    }

    /**
     * Sets c_error_message
     *
     * @param string $c_error_message c_error_message
     *
     * @return $this
     */
    public function setCErrorMessage($c_error_message)
    {
        $this->container['c_error_message'] = $c_error_message;

        return $this;
    }

    /**
     * Gets t_outfieldvalue
     *
     * @return \Swagger\Client\Model\TOutfieldvalueResp
     */
    public function getTOutfieldvalue()
    {
        return $this->container['t_outfieldvalue'];
    }

    /**
     * Sets t_outfieldvalue
     *
     * @param \Swagger\Client\Model\TOutfieldvalueResp $t_outfieldvalue t_outfieldvalue
     *
     * @return $this
     */
    public function setTOutfieldvalue($t_outfieldvalue)
    {
        $this->container['t_outfieldvalue'] = $t_outfieldvalue;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


