<?php
/**
 * SxapiOeitm
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SxapiOeitm Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SxapiOeitm implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'sxapi_oeitm';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'line_iden' => 'string',
        'qty_uom' => 'string',
        'prod_svc_cd' => 'string',
        'seller_prod' => 'string',
        'buyer_prod' => 'string',
        'descrip' => 'string',
        'user1' => 'string',
        'user2' => 'string',
        'user3' => 'string',
        'user4' => 'string',
        'user5' => 'string',
        'ord_stat_cd' => 'string',
        'chg_cd' => 'string',
        'bo_type' => 'string',
        'user6' => 'string',
        'user7' => 'string',
        'user8' => 'string',
        'user9' => 'string',
        'user10' => 'string',
        'spec_cost_ty' => 'string',
        's_cost_unit' => 'string',
        'xref_prod_ty' => 'string',
        'taxable_fl' => 'string',
        'taxable_ty' => 'string',
        'tax_group' => 'string',
        'promise_dt' => 'string',
        'req_ship_dt' => 'string',
        'spec_ns_type' => 'string',
        'upc' => 'string',
        'sx_line_no' => 'string',
        'qty_ship' => 'string',
        'price' => 'string',
        'disc_pct' => 'string',
        'qty_ord' => 'string',
        'disc_amt' => 'string',
        'tax_amt1' => 'string',
        'tax_amt2' => 'string',
        'tax_amt3' => 'string',
        'tax_amt4' => 'string',
        'upc_section1' => 'string',
        'upc_section2' => 'string',
        'upc_section3' => 'string',
        'upc_section4' => 'string',
        'upc_section5' => 'string',
        'upc_section6' => 'string',
        'restock_chg' => 'string',
        'sp_cost_unit' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'line_iden' => null,
        'qty_uom' => null,
        'prod_svc_cd' => null,
        'seller_prod' => null,
        'buyer_prod' => null,
        'descrip' => null,
        'user1' => null,
        'user2' => null,
        'user3' => null,
        'user4' => null,
        'user5' => null,
        'ord_stat_cd' => null,
        'chg_cd' => null,
        'bo_type' => null,
        'user6' => null,
        'user7' => null,
        'user8' => null,
        'user9' => null,
        'user10' => null,
        'spec_cost_ty' => null,
        's_cost_unit' => null,
        'xref_prod_ty' => null,
        'taxable_fl' => null,
        'taxable_ty' => null,
        'tax_group' => null,
        'promise_dt' => null,
        'req_ship_dt' => null,
        'spec_ns_type' => null,
        'upc' => null,
        'sx_line_no' => null,
        'qty_ship' => null,
        'price' => null,
        'disc_pct' => null,
        'qty_ord' => null,
        'disc_amt' => null,
        'tax_amt1' => null,
        'tax_amt2' => null,
        'tax_amt3' => null,
        'tax_amt4' => null,
        'upc_section1' => null,
        'upc_section2' => null,
        'upc_section3' => null,
        'upc_section4' => null,
        'upc_section5' => null,
        'upc_section6' => null,
        'restock_chg' => null,
        'sp_cost_unit' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'line_iden' => 'lineIden',
        'qty_uom' => 'qtyUom',
        'prod_svc_cd' => 'prodSvcCd',
        'seller_prod' => 'sellerProd',
        'buyer_prod' => 'buyerProd',
        'descrip' => 'descrip',
        'user1' => 'user1',
        'user2' => 'user2',
        'user3' => 'user3',
        'user4' => 'user4',
        'user5' => 'user5',
        'ord_stat_cd' => 'ordStatCd',
        'chg_cd' => 'chgCd',
        'bo_type' => 'boType',
        'user6' => 'user6',
        'user7' => 'user7',
        'user8' => 'user8',
        'user9' => 'user9',
        'user10' => 'user10',
        'spec_cost_ty' => 'specCostTy',
        's_cost_unit' => 'sCostUnit',
        'xref_prod_ty' => 'xrefProdTy',
        'taxable_fl' => 'taxableFl',
        'taxable_ty' => 'taxableTy',
        'tax_group' => 'taxGroup',
        'promise_dt' => 'promiseDt',
        'req_ship_dt' => 'reqShipDt',
        'spec_ns_type' => 'specNsType',
        'upc' => 'upc',
        'sx_line_no' => 'sxLineNo',
        'qty_ship' => 'qtyShip',
        'price' => 'price',
        'disc_pct' => 'discPct',
        'qty_ord' => 'qtyOrd',
        'disc_amt' => 'discAmt',
        'tax_amt1' => 'taxAmt1',
        'tax_amt2' => 'taxAmt2',
        'tax_amt3' => 'taxAmt3',
        'tax_amt4' => 'taxAmt4',
        'upc_section1' => 'upcSection1',
        'upc_section2' => 'upcSection2',
        'upc_section3' => 'upcSection3',
        'upc_section4' => 'upcSection4',
        'upc_section5' => 'upcSection5',
        'upc_section6' => 'upcSection6',
        'restock_chg' => 'restockChg',
        'sp_cost_unit' => 'spCostUnit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'line_iden' => 'setLineIden',
        'qty_uom' => 'setQtyUom',
        'prod_svc_cd' => 'setProdSvcCd',
        'seller_prod' => 'setSellerProd',
        'buyer_prod' => 'setBuyerProd',
        'descrip' => 'setDescrip',
        'user1' => 'setUser1',
        'user2' => 'setUser2',
        'user3' => 'setUser3',
        'user4' => 'setUser4',
        'user5' => 'setUser5',
        'ord_stat_cd' => 'setOrdStatCd',
        'chg_cd' => 'setChgCd',
        'bo_type' => 'setBoType',
        'user6' => 'setUser6',
        'user7' => 'setUser7',
        'user8' => 'setUser8',
        'user9' => 'setUser9',
        'user10' => 'setUser10',
        'spec_cost_ty' => 'setSpecCostTy',
        's_cost_unit' => 'setSCostUnit',
        'xref_prod_ty' => 'setXrefProdTy',
        'taxable_fl' => 'setTaxableFl',
        'taxable_ty' => 'setTaxableTy',
        'tax_group' => 'setTaxGroup',
        'promise_dt' => 'setPromiseDt',
        'req_ship_dt' => 'setReqShipDt',
        'spec_ns_type' => 'setSpecNsType',
        'upc' => 'setUpc',
        'sx_line_no' => 'setSxLineNo',
        'qty_ship' => 'setQtyShip',
        'price' => 'setPrice',
        'disc_pct' => 'setDiscPct',
        'qty_ord' => 'setQtyOrd',
        'disc_amt' => 'setDiscAmt',
        'tax_amt1' => 'setTaxAmt1',
        'tax_amt2' => 'setTaxAmt2',
        'tax_amt3' => 'setTaxAmt3',
        'tax_amt4' => 'setTaxAmt4',
        'upc_section1' => 'setUpcSection1',
        'upc_section2' => 'setUpcSection2',
        'upc_section3' => 'setUpcSection3',
        'upc_section4' => 'setUpcSection4',
        'upc_section5' => 'setUpcSection5',
        'upc_section6' => 'setUpcSection6',
        'restock_chg' => 'setRestockChg',
        'sp_cost_unit' => 'setSpCostUnit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'line_iden' => 'getLineIden',
        'qty_uom' => 'getQtyUom',
        'prod_svc_cd' => 'getProdSvcCd',
        'seller_prod' => 'getSellerProd',
        'buyer_prod' => 'getBuyerProd',
        'descrip' => 'getDescrip',
        'user1' => 'getUser1',
        'user2' => 'getUser2',
        'user3' => 'getUser3',
        'user4' => 'getUser4',
        'user5' => 'getUser5',
        'ord_stat_cd' => 'getOrdStatCd',
        'chg_cd' => 'getChgCd',
        'bo_type' => 'getBoType',
        'user6' => 'getUser6',
        'user7' => 'getUser7',
        'user8' => 'getUser8',
        'user9' => 'getUser9',
        'user10' => 'getUser10',
        'spec_cost_ty' => 'getSpecCostTy',
        's_cost_unit' => 'getSCostUnit',
        'xref_prod_ty' => 'getXrefProdTy',
        'taxable_fl' => 'getTaxableFl',
        'taxable_ty' => 'getTaxableTy',
        'tax_group' => 'getTaxGroup',
        'promise_dt' => 'getPromiseDt',
        'req_ship_dt' => 'getReqShipDt',
        'spec_ns_type' => 'getSpecNsType',
        'upc' => 'getUpc',
        'sx_line_no' => 'getSxLineNo',
        'qty_ship' => 'getQtyShip',
        'price' => 'getPrice',
        'disc_pct' => 'getDiscPct',
        'qty_ord' => 'getQtyOrd',
        'disc_amt' => 'getDiscAmt',
        'tax_amt1' => 'getTaxAmt1',
        'tax_amt2' => 'getTaxAmt2',
        'tax_amt3' => 'getTaxAmt3',
        'tax_amt4' => 'getTaxAmt4',
        'upc_section1' => 'getUpcSection1',
        'upc_section2' => 'getUpcSection2',
        'upc_section3' => 'getUpcSection3',
        'upc_section4' => 'getUpcSection4',
        'upc_section5' => 'getUpcSection5',
        'upc_section6' => 'getUpcSection6',
        'restock_chg' => 'getRestockChg',
        'sp_cost_unit' => 'getSpCostUnit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['line_iden'] = isset($data['line_iden']) ? $data['line_iden'] : null;
        $this->container['qty_uom'] = isset($data['qty_uom']) ? $data['qty_uom'] : null;
        $this->container['prod_svc_cd'] = isset($data['prod_svc_cd']) ? $data['prod_svc_cd'] : null;
        $this->container['seller_prod'] = isset($data['seller_prod']) ? $data['seller_prod'] : null;
        $this->container['buyer_prod'] = isset($data['buyer_prod']) ? $data['buyer_prod'] : null;
        $this->container['descrip'] = isset($data['descrip']) ? $data['descrip'] : null;
        $this->container['user1'] = isset($data['user1']) ? $data['user1'] : null;
        $this->container['user2'] = isset($data['user2']) ? $data['user2'] : null;
        $this->container['user3'] = isset($data['user3']) ? $data['user3'] : null;
        $this->container['user4'] = isset($data['user4']) ? $data['user4'] : null;
        $this->container['user5'] = isset($data['user5']) ? $data['user5'] : null;
        $this->container['ord_stat_cd'] = isset($data['ord_stat_cd']) ? $data['ord_stat_cd'] : null;
        $this->container['chg_cd'] = isset($data['chg_cd']) ? $data['chg_cd'] : null;
        $this->container['bo_type'] = isset($data['bo_type']) ? $data['bo_type'] : null;
        $this->container['user6'] = isset($data['user6']) ? $data['user6'] : null;
        $this->container['user7'] = isset($data['user7']) ? $data['user7'] : null;
        $this->container['user8'] = isset($data['user8']) ? $data['user8'] : null;
        $this->container['user9'] = isset($data['user9']) ? $data['user9'] : null;
        $this->container['user10'] = isset($data['user10']) ? $data['user10'] : null;
        $this->container['spec_cost_ty'] = isset($data['spec_cost_ty']) ? $data['spec_cost_ty'] : null;
        $this->container['s_cost_unit'] = isset($data['s_cost_unit']) ? $data['s_cost_unit'] : null;
        $this->container['xref_prod_ty'] = isset($data['xref_prod_ty']) ? $data['xref_prod_ty'] : null;
        $this->container['taxable_fl'] = isset($data['taxable_fl']) ? $data['taxable_fl'] : null;
        $this->container['taxable_ty'] = isset($data['taxable_ty']) ? $data['taxable_ty'] : null;
        $this->container['tax_group'] = isset($data['tax_group']) ? $data['tax_group'] : null;
        $this->container['promise_dt'] = isset($data['promise_dt']) ? $data['promise_dt'] : null;
        $this->container['req_ship_dt'] = isset($data['req_ship_dt']) ? $data['req_ship_dt'] : null;
        $this->container['spec_ns_type'] = isset($data['spec_ns_type']) ? $data['spec_ns_type'] : null;
        $this->container['upc'] = isset($data['upc']) ? $data['upc'] : null;
        $this->container['sx_line_no'] = isset($data['sx_line_no']) ? $data['sx_line_no'] : null;
        $this->container['qty_ship'] = isset($data['qty_ship']) ? $data['qty_ship'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['disc_pct'] = isset($data['disc_pct']) ? $data['disc_pct'] : null;
        $this->container['qty_ord'] = isset($data['qty_ord']) ? $data['qty_ord'] : null;
        $this->container['disc_amt'] = isset($data['disc_amt']) ? $data['disc_amt'] : null;
        $this->container['tax_amt1'] = isset($data['tax_amt1']) ? $data['tax_amt1'] : null;
        $this->container['tax_amt2'] = isset($data['tax_amt2']) ? $data['tax_amt2'] : null;
        $this->container['tax_amt3'] = isset($data['tax_amt3']) ? $data['tax_amt3'] : null;
        $this->container['tax_amt4'] = isset($data['tax_amt4']) ? $data['tax_amt4'] : null;
        $this->container['upc_section1'] = isset($data['upc_section1']) ? $data['upc_section1'] : null;
        $this->container['upc_section2'] = isset($data['upc_section2']) ? $data['upc_section2'] : null;
        $this->container['upc_section3'] = isset($data['upc_section3']) ? $data['upc_section3'] : null;
        $this->container['upc_section4'] = isset($data['upc_section4']) ? $data['upc_section4'] : null;
        $this->container['upc_section5'] = isset($data['upc_section5']) ? $data['upc_section5'] : null;
        $this->container['upc_section6'] = isset($data['upc_section6']) ? $data['upc_section6'] : null;
        $this->container['restock_chg'] = isset($data['restock_chg']) ? $data['restock_chg'] : null;
        $this->container['sp_cost_unit'] = isset($data['sp_cost_unit']) ? $data['sp_cost_unit'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets line_iden
     *
     * @return string
     */
    public function getLineIden()
    {
        return $this->container['line_iden'];
    }

    /**
     * Sets line_iden
     *
     * @param string $line_iden line_iden
     *
     * @return $this
     */
    public function setLineIden($line_iden)
    {
        $this->container['line_iden'] = $line_iden;

        return $this;
    }

    /**
     * Gets qty_uom
     *
     * @return string
     */
    public function getQtyUom()
    {
        return $this->container['qty_uom'];
    }

    /**
     * Sets qty_uom
     *
     * @param string $qty_uom qty_uom
     *
     * @return $this
     */
    public function setQtyUom($qty_uom)
    {
        $this->container['qty_uom'] = $qty_uom;

        return $this;
    }

    /**
     * Gets prod_svc_cd
     *
     * @return string
     */
    public function getProdSvcCd()
    {
        return $this->container['prod_svc_cd'];
    }

    /**
     * Sets prod_svc_cd
     *
     * @param string $prod_svc_cd prod_svc_cd
     *
     * @return $this
     */
    public function setProdSvcCd($prod_svc_cd)
    {
        $this->container['prod_svc_cd'] = $prod_svc_cd;

        return $this;
    }

    /**
     * Gets seller_prod
     *
     * @return string
     */
    public function getSellerProd()
    {
        return $this->container['seller_prod'];
    }

    /**
     * Sets seller_prod
     *
     * @param string $seller_prod seller_prod
     *
     * @return $this
     */
    public function setSellerProd($seller_prod)
    {
        $this->container['seller_prod'] = $seller_prod;

        return $this;
    }

    /**
     * Gets buyer_prod
     *
     * @return string
     */
    public function getBuyerProd()
    {
        return $this->container['buyer_prod'];
    }

    /**
     * Sets buyer_prod
     *
     * @param string $buyer_prod buyer_prod
     *
     * @return $this
     */
    public function setBuyerProd($buyer_prod)
    {
        $this->container['buyer_prod'] = $buyer_prod;

        return $this;
    }

    /**
     * Gets descrip
     *
     * @return string
     */
    public function getDescrip()
    {
        return $this->container['descrip'];
    }

    /**
     * Sets descrip
     *
     * @param string $descrip descrip
     *
     * @return $this
     */
    public function setDescrip($descrip)
    {
        $this->container['descrip'] = $descrip;

        return $this;
    }

    /**
     * Gets user1
     *
     * @return string
     */
    public function getUser1()
    {
        return $this->container['user1'];
    }

    /**
     * Sets user1
     *
     * @param string $user1 user1
     *
     * @return $this
     */
    public function setUser1($user1)
    {
        $this->container['user1'] = $user1;

        return $this;
    }

    /**
     * Gets user2
     *
     * @return string
     */
    public function getUser2()
    {
        return $this->container['user2'];
    }

    /**
     * Sets user2
     *
     * @param string $user2 user2
     *
     * @return $this
     */
    public function setUser2($user2)
    {
        $this->container['user2'] = $user2;

        return $this;
    }

    /**
     * Gets user3
     *
     * @return string
     */
    public function getUser3()
    {
        return $this->container['user3'];
    }

    /**
     * Sets user3
     *
     * @param string $user3 user3
     *
     * @return $this
     */
    public function setUser3($user3)
    {
        $this->container['user3'] = $user3;

        return $this;
    }

    /**
     * Gets user4
     *
     * @return string
     */
    public function getUser4()
    {
        return $this->container['user4'];
    }

    /**
     * Sets user4
     *
     * @param string $user4 user4
     *
     * @return $this
     */
    public function setUser4($user4)
    {
        $this->container['user4'] = $user4;

        return $this;
    }

    /**
     * Gets user5
     *
     * @return string
     */
    public function getUser5()
    {
        return $this->container['user5'];
    }

    /**
     * Sets user5
     *
     * @param string $user5 user5
     *
     * @return $this
     */
    public function setUser5($user5)
    {
        $this->container['user5'] = $user5;

        return $this;
    }

    /**
     * Gets ord_stat_cd
     *
     * @return string
     */
    public function getOrdStatCd()
    {
        return $this->container['ord_stat_cd'];
    }

    /**
     * Sets ord_stat_cd
     *
     * @param string $ord_stat_cd ord_stat_cd
     *
     * @return $this
     */
    public function setOrdStatCd($ord_stat_cd)
    {
        $this->container['ord_stat_cd'] = $ord_stat_cd;

        return $this;
    }

    /**
     * Gets chg_cd
     *
     * @return string
     */
    public function getChgCd()
    {
        return $this->container['chg_cd'];
    }

    /**
     * Sets chg_cd
     *
     * @param string $chg_cd chg_cd
     *
     * @return $this
     */
    public function setChgCd($chg_cd)
    {
        $this->container['chg_cd'] = $chg_cd;

        return $this;
    }

    /**
     * Gets bo_type
     *
     * @return string
     */
    public function getBoType()
    {
        return $this->container['bo_type'];
    }

    /**
     * Sets bo_type
     *
     * @param string $bo_type bo_type
     *
     * @return $this
     */
    public function setBoType($bo_type)
    {
        $this->container['bo_type'] = $bo_type;

        return $this;
    }

    /**
     * Gets user6
     *
     * @return string
     */
    public function getUser6()
    {
        return $this->container['user6'];
    }

    /**
     * Sets user6
     *
     * @param string $user6 user6
     *
     * @return $this
     */
    public function setUser6($user6)
    {
        $this->container['user6'] = $user6;

        return $this;
    }

    /**
     * Gets user7
     *
     * @return string
     */
    public function getUser7()
    {
        return $this->container['user7'];
    }

    /**
     * Sets user7
     *
     * @param string $user7 user7
     *
     * @return $this
     */
    public function setUser7($user7)
    {
        $this->container['user7'] = $user7;

        return $this;
    }

    /**
     * Gets user8
     *
     * @return string
     */
    public function getUser8()
    {
        return $this->container['user8'];
    }

    /**
     * Sets user8
     *
     * @param string $user8 user8
     *
     * @return $this
     */
    public function setUser8($user8)
    {
        $this->container['user8'] = $user8;

        return $this;
    }

    /**
     * Gets user9
     *
     * @return string
     */
    public function getUser9()
    {
        return $this->container['user9'];
    }

    /**
     * Sets user9
     *
     * @param string $user9 user9
     *
     * @return $this
     */
    public function setUser9($user9)
    {
        $this->container['user9'] = $user9;

        return $this;
    }

    /**
     * Gets user10
     *
     * @return string
     */
    public function getUser10()
    {
        return $this->container['user10'];
    }

    /**
     * Sets user10
     *
     * @param string $user10 user10
     *
     * @return $this
     */
    public function setUser10($user10)
    {
        $this->container['user10'] = $user10;

        return $this;
    }

    /**
     * Gets spec_cost_ty
     *
     * @return string
     */
    public function getSpecCostTy()
    {
        return $this->container['spec_cost_ty'];
    }

    /**
     * Sets spec_cost_ty
     *
     * @param string $spec_cost_ty spec_cost_ty
     *
     * @return $this
     */
    public function setSpecCostTy($spec_cost_ty)
    {
        $this->container['spec_cost_ty'] = $spec_cost_ty;

        return $this;
    }

    /**
     * Gets s_cost_unit
     *
     * @return string
     */
    public function getSCostUnit()
    {
        return $this->container['s_cost_unit'];
    }

    /**
     * Sets s_cost_unit
     *
     * @param string $s_cost_unit s_cost_unit
     *
     * @return $this
     */
    public function setSCostUnit($s_cost_unit)
    {
        $this->container['s_cost_unit'] = $s_cost_unit;

        return $this;
    }

    /**
     * Gets xref_prod_ty
     *
     * @return string
     */
    public function getXrefProdTy()
    {
        return $this->container['xref_prod_ty'];
    }

    /**
     * Sets xref_prod_ty
     *
     * @param string $xref_prod_ty xref_prod_ty
     *
     * @return $this
     */
    public function setXrefProdTy($xref_prod_ty)
    {
        $this->container['xref_prod_ty'] = $xref_prod_ty;

        return $this;
    }

    /**
     * Gets taxable_fl
     *
     * @return string
     */
    public function getTaxableFl()
    {
        return $this->container['taxable_fl'];
    }

    /**
     * Sets taxable_fl
     *
     * @param string $taxable_fl taxable_fl
     *
     * @return $this
     */
    public function setTaxableFl($taxable_fl)
    {
        $this->container['taxable_fl'] = $taxable_fl;

        return $this;
    }

    /**
     * Gets taxable_ty
     *
     * @return string
     */
    public function getTaxableTy()
    {
        return $this->container['taxable_ty'];
    }

    /**
     * Sets taxable_ty
     *
     * @param string $taxable_ty taxable_ty
     *
     * @return $this
     */
    public function setTaxableTy($taxable_ty)
    {
        $this->container['taxable_ty'] = $taxable_ty;

        return $this;
    }

    /**
     * Gets tax_group
     *
     * @return string
     */
    public function getTaxGroup()
    {
        return $this->container['tax_group'];
    }

    /**
     * Sets tax_group
     *
     * @param string $tax_group tax_group
     *
     * @return $this
     */
    public function setTaxGroup($tax_group)
    {
        $this->container['tax_group'] = $tax_group;

        return $this;
    }

    /**
     * Gets promise_dt
     *
     * @return string
     */
    public function getPromiseDt()
    {
        return $this->container['promise_dt'];
    }

    /**
     * Sets promise_dt
     *
     * @param string $promise_dt promise_dt
     *
     * @return $this
     */
    public function setPromiseDt($promise_dt)
    {
        $this->container['promise_dt'] = $promise_dt;

        return $this;
    }

    /**
     * Gets req_ship_dt
     *
     * @return string
     */
    public function getReqShipDt()
    {
        return $this->container['req_ship_dt'];
    }

    /**
     * Sets req_ship_dt
     *
     * @param string $req_ship_dt req_ship_dt
     *
     * @return $this
     */
    public function setReqShipDt($req_ship_dt)
    {
        $this->container['req_ship_dt'] = $req_ship_dt;

        return $this;
    }

    /**
     * Gets spec_ns_type
     *
     * @return string
     */
    public function getSpecNsType()
    {
        return $this->container['spec_ns_type'];
    }

    /**
     * Sets spec_ns_type
     *
     * @param string $spec_ns_type spec_ns_type
     *
     * @return $this
     */
    public function setSpecNsType($spec_ns_type)
    {
        $this->container['spec_ns_type'] = $spec_ns_type;

        return $this;
    }

    /**
     * Gets upc
     *
     * @return string
     */
    public function getUpc()
    {
        return $this->container['upc'];
    }

    /**
     * Sets upc
     *
     * @param string $upc upc
     *
     * @return $this
     */
    public function setUpc($upc)
    {
        $this->container['upc'] = $upc;

        return $this;
    }

    /**
     * Gets sx_line_no
     *
     * @return string
     */
    public function getSxLineNo()
    {
        return $this->container['sx_line_no'];
    }

    /**
     * Sets sx_line_no
     *
     * @param string $sx_line_no sx_line_no
     *
     * @return $this
     */
    public function setSxLineNo($sx_line_no)
    {
        $this->container['sx_line_no'] = $sx_line_no;

        return $this;
    }

    /**
     * Gets qty_ship
     *
     * @return string
     */
    public function getQtyShip()
    {
        return $this->container['qty_ship'];
    }

    /**
     * Sets qty_ship
     *
     * @param string $qty_ship qty_ship
     *
     * @return $this
     */
    public function setQtyShip($qty_ship)
    {
        $this->container['qty_ship'] = $qty_ship;

        return $this;
    }

    /**
     * Gets price
     *
     * @return string
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param string $price price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets disc_pct
     *
     * @return string
     */
    public function getDiscPct()
    {
        return $this->container['disc_pct'];
    }

    /**
     * Sets disc_pct
     *
     * @param string $disc_pct disc_pct
     *
     * @return $this
     */
    public function setDiscPct($disc_pct)
    {
        $this->container['disc_pct'] = $disc_pct;

        return $this;
    }

    /**
     * Gets qty_ord
     *
     * @return string
     */
    public function getQtyOrd()
    {
        return $this->container['qty_ord'];
    }

    /**
     * Sets qty_ord
     *
     * @param string $qty_ord qty_ord
     *
     * @return $this
     */
    public function setQtyOrd($qty_ord)
    {
        $this->container['qty_ord'] = $qty_ord;

        return $this;
    }

    /**
     * Gets disc_amt
     *
     * @return string
     */
    public function getDiscAmt()
    {
        return $this->container['disc_amt'];
    }

    /**
     * Sets disc_amt
     *
     * @param string $disc_amt disc_amt
     *
     * @return $this
     */
    public function setDiscAmt($disc_amt)
    {
        $this->container['disc_amt'] = $disc_amt;

        return $this;
    }

    /**
     * Gets tax_amt1
     *
     * @return string
     */
    public function getTaxAmt1()
    {
        return $this->container['tax_amt1'];
    }

    /**
     * Sets tax_amt1
     *
     * @param string $tax_amt1 tax_amt1
     *
     * @return $this
     */
    public function setTaxAmt1($tax_amt1)
    {
        $this->container['tax_amt1'] = $tax_amt1;

        return $this;
    }

    /**
     * Gets tax_amt2
     *
     * @return string
     */
    public function getTaxAmt2()
    {
        return $this->container['tax_amt2'];
    }

    /**
     * Sets tax_amt2
     *
     * @param string $tax_amt2 tax_amt2
     *
     * @return $this
     */
    public function setTaxAmt2($tax_amt2)
    {
        $this->container['tax_amt2'] = $tax_amt2;

        return $this;
    }

    /**
     * Gets tax_amt3
     *
     * @return string
     */
    public function getTaxAmt3()
    {
        return $this->container['tax_amt3'];
    }

    /**
     * Sets tax_amt3
     *
     * @param string $tax_amt3 tax_amt3
     *
     * @return $this
     */
    public function setTaxAmt3($tax_amt3)
    {
        $this->container['tax_amt3'] = $tax_amt3;

        return $this;
    }

    /**
     * Gets tax_amt4
     *
     * @return string
     */
    public function getTaxAmt4()
    {
        return $this->container['tax_amt4'];
    }

    /**
     * Sets tax_amt4
     *
     * @param string $tax_amt4 tax_amt4
     *
     * @return $this
     */
    public function setTaxAmt4($tax_amt4)
    {
        $this->container['tax_amt4'] = $tax_amt4;

        return $this;
    }

    /**
     * Gets upc_section1
     *
     * @return string
     */
    public function getUpcSection1()
    {
        return $this->container['upc_section1'];
    }

    /**
     * Sets upc_section1
     *
     * @param string $upc_section1 upc_section1
     *
     * @return $this
     */
    public function setUpcSection1($upc_section1)
    {
        $this->container['upc_section1'] = $upc_section1;

        return $this;
    }

    /**
     * Gets upc_section2
     *
     * @return string
     */
    public function getUpcSection2()
    {
        return $this->container['upc_section2'];
    }

    /**
     * Sets upc_section2
     *
     * @param string $upc_section2 upc_section2
     *
     * @return $this
     */
    public function setUpcSection2($upc_section2)
    {
        $this->container['upc_section2'] = $upc_section2;

        return $this;
    }

    /**
     * Gets upc_section3
     *
     * @return string
     */
    public function getUpcSection3()
    {
        return $this->container['upc_section3'];
    }

    /**
     * Sets upc_section3
     *
     * @param string $upc_section3 upc_section3
     *
     * @return $this
     */
    public function setUpcSection3($upc_section3)
    {
        $this->container['upc_section3'] = $upc_section3;

        return $this;
    }

    /**
     * Gets upc_section4
     *
     * @return string
     */
    public function getUpcSection4()
    {
        return $this->container['upc_section4'];
    }

    /**
     * Sets upc_section4
     *
     * @param string $upc_section4 upc_section4
     *
     * @return $this
     */
    public function setUpcSection4($upc_section4)
    {
        $this->container['upc_section4'] = $upc_section4;

        return $this;
    }

    /**
     * Gets upc_section5
     *
     * @return string
     */
    public function getUpcSection5()
    {
        return $this->container['upc_section5'];
    }

    /**
     * Sets upc_section5
     *
     * @param string $upc_section5 upc_section5
     *
     * @return $this
     */
    public function setUpcSection5($upc_section5)
    {
        $this->container['upc_section5'] = $upc_section5;

        return $this;
    }

    /**
     * Gets upc_section6
     *
     * @return string
     */
    public function getUpcSection6()
    {
        return $this->container['upc_section6'];
    }

    /**
     * Sets upc_section6
     *
     * @param string $upc_section6 upc_section6
     *
     * @return $this
     */
    public function setUpcSection6($upc_section6)
    {
        $this->container['upc_section6'] = $upc_section6;

        return $this;
    }

    /**
     * Gets restock_chg
     *
     * @return string
     */
    public function getRestockChg()
    {
        return $this->container['restock_chg'];
    }

    /**
     * Sets restock_chg
     *
     * @param string $restock_chg restock_chg
     *
     * @return $this
     */
    public function setRestockChg($restock_chg)
    {
        $this->container['restock_chg'] = $restock_chg;

        return $this;
    }

    /**
     * Gets sp_cost_unit
     *
     * @return string
     */
    public function getSpCostUnit()
    {
        return $this->container['sp_cost_unit'];
    }

    /**
     * Sets sp_cost_unit
     *
     * @param string $sp_cost_unit sp_cost_unit
     *
     * @return $this
     */
    public function setSpCostUnit($sp_cost_unit)
    {
        $this->container['sp_cost_unit'] = $sp_cost_unit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


