<?php
/**
 * SxapietccpoacknowledgementRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SxapietccpoacknowledgementRequest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SxapietccpoacknowledgementRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'sxapietccpoacknowledgement_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'company_number' => 'int',
        'operator_init' => 'string',
        'operator_password' => 'string',
        'purchase_order_number' => 'int',
        'purchase_order_suffix' => 'int',
        'extra_parameter' => 'string',
        't_inpoackheader' => '\Swagger\Client\Model\TInpoackheaderReq',
        't_inpoackline' => '\Swagger\Client\Model\TInpoacklineReq'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'company_number' => 'int64',
        'operator_init' => null,
        'operator_password' => null,
        'purchase_order_number' => 'int64',
        'purchase_order_suffix' => 'int64',
        'extra_parameter' => null,
        't_inpoackheader' => null,
        't_inpoackline' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'company_number' => 'companyNumber',
        'operator_init' => 'operatorInit',
        'operator_password' => 'operatorPassword',
        'purchase_order_number' => 'purchaseOrderNumber',
        'purchase_order_suffix' => 'purchaseOrderSuffix',
        'extra_parameter' => 'extraParameter',
        't_inpoackheader' => 'tInpoackheader',
        't_inpoackline' => 'tInpoackline'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'company_number' => 'setCompanyNumber',
        'operator_init' => 'setOperatorInit',
        'operator_password' => 'setOperatorPassword',
        'purchase_order_number' => 'setPurchaseOrderNumber',
        'purchase_order_suffix' => 'setPurchaseOrderSuffix',
        'extra_parameter' => 'setExtraParameter',
        't_inpoackheader' => 'setTInpoackheader',
        't_inpoackline' => 'setTInpoackline'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'company_number' => 'getCompanyNumber',
        'operator_init' => 'getOperatorInit',
        'operator_password' => 'getOperatorPassword',
        'purchase_order_number' => 'getPurchaseOrderNumber',
        'purchase_order_suffix' => 'getPurchaseOrderSuffix',
        'extra_parameter' => 'getExtraParameter',
        't_inpoackheader' => 'getTInpoackheader',
        't_inpoackline' => 'getTInpoackline'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['company_number'] = isset($data['company_number']) ? $data['company_number'] : null;
        $this->container['operator_init'] = isset($data['operator_init']) ? $data['operator_init'] : null;
        $this->container['operator_password'] = isset($data['operator_password']) ? $data['operator_password'] : null;
        $this->container['purchase_order_number'] = isset($data['purchase_order_number']) ? $data['purchase_order_number'] : null;
        $this->container['purchase_order_suffix'] = isset($data['purchase_order_suffix']) ? $data['purchase_order_suffix'] : null;
        $this->container['extra_parameter'] = isset($data['extra_parameter']) ? $data['extra_parameter'] : null;
        $this->container['t_inpoackheader'] = isset($data['t_inpoackheader']) ? $data['t_inpoackheader'] : null;
        $this->container['t_inpoackline'] = isset($data['t_inpoackline']) ? $data['t_inpoackline'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets company_number
     *
     * @return int
     */
    public function getCompanyNumber()
    {
        return $this->container['company_number'];
    }

    /**
     * Sets company_number
     *
     * @param int $company_number company_number
     *
     * @return $this
     */
    public function setCompanyNumber($company_number)
    {
        $this->container['company_number'] = $company_number;

        return $this;
    }

    /**
     * Gets operator_init
     *
     * @return string
     */
    public function getOperatorInit()
    {
        return $this->container['operator_init'];
    }

    /**
     * Sets operator_init
     *
     * @param string $operator_init operator_init
     *
     * @return $this
     */
    public function setOperatorInit($operator_init)
    {
        $this->container['operator_init'] = $operator_init;

        return $this;
    }

    /**
     * Gets operator_password
     *
     * @return string
     */
    public function getOperatorPassword()
    {
        return $this->container['operator_password'];
    }

    /**
     * Sets operator_password
     *
     * @param string $operator_password operator_password
     *
     * @return $this
     */
    public function setOperatorPassword($operator_password)
    {
        $this->container['operator_password'] = $operator_password;

        return $this;
    }

    /**
     * Gets purchase_order_number
     *
     * @return int
     */
    public function getPurchaseOrderNumber()
    {
        return $this->container['purchase_order_number'];
    }

    /**
     * Sets purchase_order_number
     *
     * @param int $purchase_order_number purchase_order_number
     *
     * @return $this
     */
    public function setPurchaseOrderNumber($purchase_order_number)
    {
        $this->container['purchase_order_number'] = $purchase_order_number;

        return $this;
    }

    /**
     * Gets purchase_order_suffix
     *
     * @return int
     */
    public function getPurchaseOrderSuffix()
    {
        return $this->container['purchase_order_suffix'];
    }

    /**
     * Sets purchase_order_suffix
     *
     * @param int $purchase_order_suffix purchase_order_suffix
     *
     * @return $this
     */
    public function setPurchaseOrderSuffix($purchase_order_suffix)
    {
        $this->container['purchase_order_suffix'] = $purchase_order_suffix;

        return $this;
    }

    /**
     * Gets extra_parameter
     *
     * @return string
     */
    public function getExtraParameter()
    {
        return $this->container['extra_parameter'];
    }

    /**
     * Sets extra_parameter
     *
     * @param string $extra_parameter extra_parameter
     *
     * @return $this
     */
    public function setExtraParameter($extra_parameter)
    {
        $this->container['extra_parameter'] = $extra_parameter;

        return $this;
    }

    /**
     * Gets t_inpoackheader
     *
     * @return \Swagger\Client\Model\TInpoackheaderReq
     */
    public function getTInpoackheader()
    {
        return $this->container['t_inpoackheader'];
    }

    /**
     * Sets t_inpoackheader
     *
     * @param \Swagger\Client\Model\TInpoackheaderReq $t_inpoackheader t_inpoackheader
     *
     * @return $this
     */
    public function setTInpoackheader($t_inpoackheader)
    {
        $this->container['t_inpoackheader'] = $t_inpoackheader;

        return $this;
    }

    /**
     * Gets t_inpoackline
     *
     * @return \Swagger\Client\Model\TInpoacklineReq
     */
    public function getTInpoackline()
    {
        return $this->container['t_inpoackline'];
    }

    /**
     * Sets t_inpoackline
     *
     * @param \Swagger\Client\Model\TInpoacklineReq $t_inpoackline t_inpoackline
     *
     * @return $this
     */
    public function setTInpoackline($t_inpoackline)
    {
        $this->container['t_inpoackline'] = $t_inpoackline;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


