<?php
/**
 * TInputrebdata
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * TInputrebdata Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TInputrebdata implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 't-inputrebdata';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'actiontype' => 'string',
        'seqno' => 'int',
        'doctype' => 'string',
        'levelcd' => 'int',
        'rebatecd' => 'string',
        'vendno' => 'double',
        'edipartner' => 'string',
        'vendduns' => 'string',
        'sendersvendid' => 'string',
        'custno' => 'double',
        'custedipartner' => 'string',
        'custduns' => 'string',
        'shipto' => 'string',
        'custrebty' => 'string',
        'product' => 'string',
        'vendprod' => 'string',
        'barcodeprod' => 'string',
        'upcsection1' => 'double',
        'upcsection2' => 'double',
        'upcsection3' => 'double',
        'upcsection4' => 'double',
        'upcsection5' => 'double',
        'upcsection6' => 'double',
        'upcnumber' => 'double',
        'naedprodcd' => 'string',
        'startdt' => '\DateTime',
        'enddt' => '\DateTime',
        'whse' => 'string',
        'whseduns' => 'string',
        'region' => 'string',
        'dropshipty' => 'string',
        'contractno' => 'string',
        'contractlineno' => 'int',
        'refer' => 'string',
        'priceeffectdt' => '\DateTime',
        'priceeffectdtto' => '\DateTime',
        'pricesheet' => 'string',
        'pricesheetto' => 'string',
        'margincostty' => 'string',
        'rebatecostty' => 'string',
        'rebatepct' => 'double',
        'rebcalcty' => 'string',
        'rebdowntoty' => 'string',
        'rebateamt' => 'double',
        'contractcostfl' => 'bool',
        'capselltypefl' => 'bool',
        'sharefl' => 'bool',
        'capsellamount' => 'double',
        'sharepct' => 'double',
        'manualfl' => 'bool',
        'currencyty' => 'string',
        'caprebfl' => 'bool',
        'vendprodgrp' => 'string',
        'prodpricety' => 'string',
        'prodcat' => 'string',
        'prodline' => 'string',
        'prodrebtype' => 'string',
        'rebsubty' => 'string',
        'rebrecno' => 'int',
        'usecontractlineno' => 'bool',
        'errorfl' => 'bool',
        'errortype' => 'string',
        'setid' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'actiontype' => null,
        'seqno' => 'int64',
        'doctype' => null,
        'levelcd' => 'int64',
        'rebatecd' => null,
        'vendno' => 'double',
        'edipartner' => null,
        'vendduns' => null,
        'sendersvendid' => null,
        'custno' => 'double',
        'custedipartner' => null,
        'custduns' => null,
        'shipto' => null,
        'custrebty' => null,
        'product' => null,
        'vendprod' => null,
        'barcodeprod' => null,
        'upcsection1' => 'double',
        'upcsection2' => 'double',
        'upcsection3' => 'double',
        'upcsection4' => 'double',
        'upcsection5' => 'double',
        'upcsection6' => 'double',
        'upcnumber' => 'double',
        'naedprodcd' => null,
        'startdt' => 'date',
        'enddt' => 'date',
        'whse' => null,
        'whseduns' => null,
        'region' => null,
        'dropshipty' => null,
        'contractno' => null,
        'contractlineno' => 'int64',
        'refer' => null,
        'priceeffectdt' => 'date',
        'priceeffectdtto' => 'date',
        'pricesheet' => null,
        'pricesheetto' => null,
        'margincostty' => null,
        'rebatecostty' => null,
        'rebatepct' => 'double',
        'rebcalcty' => null,
        'rebdowntoty' => null,
        'rebateamt' => 'double',
        'contractcostfl' => null,
        'capselltypefl' => null,
        'sharefl' => null,
        'capsellamount' => 'double',
        'sharepct' => 'double',
        'manualfl' => null,
        'currencyty' => null,
        'caprebfl' => null,
        'vendprodgrp' => null,
        'prodpricety' => null,
        'prodcat' => null,
        'prodline' => null,
        'prodrebtype' => null,
        'rebsubty' => null,
        'rebrecno' => 'int64',
        'usecontractlineno' => null,
        'errorfl' => null,
        'errortype' => null,
        'setid' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'actiontype' => 'actiontype',
        'seqno' => 'seqno',
        'doctype' => 'doctype',
        'levelcd' => 'levelcd',
        'rebatecd' => 'rebatecd',
        'vendno' => 'vendno',
        'edipartner' => 'edipartner',
        'vendduns' => 'vendduns',
        'sendersvendid' => 'sendersvendid',
        'custno' => 'custno',
        'custedipartner' => 'custedipartner',
        'custduns' => 'custduns',
        'shipto' => 'shipto',
        'custrebty' => 'custrebty',
        'product' => 'product',
        'vendprod' => 'vendprod',
        'barcodeprod' => 'barcodeprod',
        'upcsection1' => 'upcsection1',
        'upcsection2' => 'upcsection2',
        'upcsection3' => 'upcsection3',
        'upcsection4' => 'upcsection4',
        'upcsection5' => 'upcsection5',
        'upcsection6' => 'upcsection6',
        'upcnumber' => 'upcnumber',
        'naedprodcd' => 'naedprodcd',
        'startdt' => 'startdt',
        'enddt' => 'enddt',
        'whse' => 'whse',
        'whseduns' => 'whseduns',
        'region' => 'region',
        'dropshipty' => 'dropshipty',
        'contractno' => 'contractno',
        'contractlineno' => 'contractlineno',
        'refer' => 'refer',
        'priceeffectdt' => 'priceeffectdt',
        'priceeffectdtto' => 'priceeffectdtto',
        'pricesheet' => 'pricesheet',
        'pricesheetto' => 'pricesheetto',
        'margincostty' => 'margincostty',
        'rebatecostty' => 'rebatecostty',
        'rebatepct' => 'rebatepct',
        'rebcalcty' => 'rebcalcty',
        'rebdowntoty' => 'rebdowntoty',
        'rebateamt' => 'rebateamt',
        'contractcostfl' => 'contractcostfl',
        'capselltypefl' => 'capselltypefl',
        'sharefl' => 'sharefl',
        'capsellamount' => 'capsellamount',
        'sharepct' => 'sharepct',
        'manualfl' => 'manualfl',
        'currencyty' => 'currencyty',
        'caprebfl' => 'caprebfl',
        'vendprodgrp' => 'vendprodgrp',
        'prodpricety' => 'prodpricety',
        'prodcat' => 'prodcat',
        'prodline' => 'prodline',
        'prodrebtype' => 'prodrebtype',
        'rebsubty' => 'rebsubty',
        'rebrecno' => 'rebrecno',
        'usecontractlineno' => 'usecontractlineno',
        'errorfl' => 'errorfl',
        'errortype' => 'errortype',
        'setid' => 'setid'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'actiontype' => 'setActiontype',
        'seqno' => 'setSeqno',
        'doctype' => 'setDoctype',
        'levelcd' => 'setLevelcd',
        'rebatecd' => 'setRebatecd',
        'vendno' => 'setVendno',
        'edipartner' => 'setEdipartner',
        'vendduns' => 'setVendduns',
        'sendersvendid' => 'setSendersvendid',
        'custno' => 'setCustno',
        'custedipartner' => 'setCustedipartner',
        'custduns' => 'setCustduns',
        'shipto' => 'setShipto',
        'custrebty' => 'setCustrebty',
        'product' => 'setProduct',
        'vendprod' => 'setVendprod',
        'barcodeprod' => 'setBarcodeprod',
        'upcsection1' => 'setUpcsection1',
        'upcsection2' => 'setUpcsection2',
        'upcsection3' => 'setUpcsection3',
        'upcsection4' => 'setUpcsection4',
        'upcsection5' => 'setUpcsection5',
        'upcsection6' => 'setUpcsection6',
        'upcnumber' => 'setUpcnumber',
        'naedprodcd' => 'setNaedprodcd',
        'startdt' => 'setStartdt',
        'enddt' => 'setEnddt',
        'whse' => 'setWhse',
        'whseduns' => 'setWhseduns',
        'region' => 'setRegion',
        'dropshipty' => 'setDropshipty',
        'contractno' => 'setContractno',
        'contractlineno' => 'setContractlineno',
        'refer' => 'setRefer',
        'priceeffectdt' => 'setPriceeffectdt',
        'priceeffectdtto' => 'setPriceeffectdtto',
        'pricesheet' => 'setPricesheet',
        'pricesheetto' => 'setPricesheetto',
        'margincostty' => 'setMargincostty',
        'rebatecostty' => 'setRebatecostty',
        'rebatepct' => 'setRebatepct',
        'rebcalcty' => 'setRebcalcty',
        'rebdowntoty' => 'setRebdowntoty',
        'rebateamt' => 'setRebateamt',
        'contractcostfl' => 'setContractcostfl',
        'capselltypefl' => 'setCapselltypefl',
        'sharefl' => 'setSharefl',
        'capsellamount' => 'setCapsellamount',
        'sharepct' => 'setSharepct',
        'manualfl' => 'setManualfl',
        'currencyty' => 'setCurrencyty',
        'caprebfl' => 'setCaprebfl',
        'vendprodgrp' => 'setVendprodgrp',
        'prodpricety' => 'setProdpricety',
        'prodcat' => 'setProdcat',
        'prodline' => 'setProdline',
        'prodrebtype' => 'setProdrebtype',
        'rebsubty' => 'setRebsubty',
        'rebrecno' => 'setRebrecno',
        'usecontractlineno' => 'setUsecontractlineno',
        'errorfl' => 'setErrorfl',
        'errortype' => 'setErrortype',
        'setid' => 'setSetid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'actiontype' => 'getActiontype',
        'seqno' => 'getSeqno',
        'doctype' => 'getDoctype',
        'levelcd' => 'getLevelcd',
        'rebatecd' => 'getRebatecd',
        'vendno' => 'getVendno',
        'edipartner' => 'getEdipartner',
        'vendduns' => 'getVendduns',
        'sendersvendid' => 'getSendersvendid',
        'custno' => 'getCustno',
        'custedipartner' => 'getCustedipartner',
        'custduns' => 'getCustduns',
        'shipto' => 'getShipto',
        'custrebty' => 'getCustrebty',
        'product' => 'getProduct',
        'vendprod' => 'getVendprod',
        'barcodeprod' => 'getBarcodeprod',
        'upcsection1' => 'getUpcsection1',
        'upcsection2' => 'getUpcsection2',
        'upcsection3' => 'getUpcsection3',
        'upcsection4' => 'getUpcsection4',
        'upcsection5' => 'getUpcsection5',
        'upcsection6' => 'getUpcsection6',
        'upcnumber' => 'getUpcnumber',
        'naedprodcd' => 'getNaedprodcd',
        'startdt' => 'getStartdt',
        'enddt' => 'getEnddt',
        'whse' => 'getWhse',
        'whseduns' => 'getWhseduns',
        'region' => 'getRegion',
        'dropshipty' => 'getDropshipty',
        'contractno' => 'getContractno',
        'contractlineno' => 'getContractlineno',
        'refer' => 'getRefer',
        'priceeffectdt' => 'getPriceeffectdt',
        'priceeffectdtto' => 'getPriceeffectdtto',
        'pricesheet' => 'getPricesheet',
        'pricesheetto' => 'getPricesheetto',
        'margincostty' => 'getMargincostty',
        'rebatecostty' => 'getRebatecostty',
        'rebatepct' => 'getRebatepct',
        'rebcalcty' => 'getRebcalcty',
        'rebdowntoty' => 'getRebdowntoty',
        'rebateamt' => 'getRebateamt',
        'contractcostfl' => 'getContractcostfl',
        'capselltypefl' => 'getCapselltypefl',
        'sharefl' => 'getSharefl',
        'capsellamount' => 'getCapsellamount',
        'sharepct' => 'getSharepct',
        'manualfl' => 'getManualfl',
        'currencyty' => 'getCurrencyty',
        'caprebfl' => 'getCaprebfl',
        'vendprodgrp' => 'getVendprodgrp',
        'prodpricety' => 'getProdpricety',
        'prodcat' => 'getProdcat',
        'prodline' => 'getProdline',
        'prodrebtype' => 'getProdrebtype',
        'rebsubty' => 'getRebsubty',
        'rebrecno' => 'getRebrecno',
        'usecontractlineno' => 'getUsecontractlineno',
        'errorfl' => 'getErrorfl',
        'errortype' => 'getErrortype',
        'setid' => 'getSetid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['actiontype'] = isset($data['actiontype']) ? $data['actiontype'] : null;
        $this->container['seqno'] = isset($data['seqno']) ? $data['seqno'] : null;
        $this->container['doctype'] = isset($data['doctype']) ? $data['doctype'] : null;
        $this->container['levelcd'] = isset($data['levelcd']) ? $data['levelcd'] : null;
        $this->container['rebatecd'] = isset($data['rebatecd']) ? $data['rebatecd'] : null;
        $this->container['vendno'] = isset($data['vendno']) ? $data['vendno'] : null;
        $this->container['edipartner'] = isset($data['edipartner']) ? $data['edipartner'] : null;
        $this->container['vendduns'] = isset($data['vendduns']) ? $data['vendduns'] : null;
        $this->container['sendersvendid'] = isset($data['sendersvendid']) ? $data['sendersvendid'] : null;
        $this->container['custno'] = isset($data['custno']) ? $data['custno'] : null;
        $this->container['custedipartner'] = isset($data['custedipartner']) ? $data['custedipartner'] : null;
        $this->container['custduns'] = isset($data['custduns']) ? $data['custduns'] : null;
        $this->container['shipto'] = isset($data['shipto']) ? $data['shipto'] : null;
        $this->container['custrebty'] = isset($data['custrebty']) ? $data['custrebty'] : null;
        $this->container['product'] = isset($data['product']) ? $data['product'] : null;
        $this->container['vendprod'] = isset($data['vendprod']) ? $data['vendprod'] : null;
        $this->container['barcodeprod'] = isset($data['barcodeprod']) ? $data['barcodeprod'] : null;
        $this->container['upcsection1'] = isset($data['upcsection1']) ? $data['upcsection1'] : null;
        $this->container['upcsection2'] = isset($data['upcsection2']) ? $data['upcsection2'] : null;
        $this->container['upcsection3'] = isset($data['upcsection3']) ? $data['upcsection3'] : null;
        $this->container['upcsection4'] = isset($data['upcsection4']) ? $data['upcsection4'] : null;
        $this->container['upcsection5'] = isset($data['upcsection5']) ? $data['upcsection5'] : null;
        $this->container['upcsection6'] = isset($data['upcsection6']) ? $data['upcsection6'] : null;
        $this->container['upcnumber'] = isset($data['upcnumber']) ? $data['upcnumber'] : null;
        $this->container['naedprodcd'] = isset($data['naedprodcd']) ? $data['naedprodcd'] : null;
        $this->container['startdt'] = isset($data['startdt']) ? $data['startdt'] : null;
        $this->container['enddt'] = isset($data['enddt']) ? $data['enddt'] : null;
        $this->container['whse'] = isset($data['whse']) ? $data['whse'] : null;
        $this->container['whseduns'] = isset($data['whseduns']) ? $data['whseduns'] : null;
        $this->container['region'] = isset($data['region']) ? $data['region'] : null;
        $this->container['dropshipty'] = isset($data['dropshipty']) ? $data['dropshipty'] : null;
        $this->container['contractno'] = isset($data['contractno']) ? $data['contractno'] : null;
        $this->container['contractlineno'] = isset($data['contractlineno']) ? $data['contractlineno'] : null;
        $this->container['refer'] = isset($data['refer']) ? $data['refer'] : null;
        $this->container['priceeffectdt'] = isset($data['priceeffectdt']) ? $data['priceeffectdt'] : null;
        $this->container['priceeffectdtto'] = isset($data['priceeffectdtto']) ? $data['priceeffectdtto'] : null;
        $this->container['pricesheet'] = isset($data['pricesheet']) ? $data['pricesheet'] : null;
        $this->container['pricesheetto'] = isset($data['pricesheetto']) ? $data['pricesheetto'] : null;
        $this->container['margincostty'] = isset($data['margincostty']) ? $data['margincostty'] : null;
        $this->container['rebatecostty'] = isset($data['rebatecostty']) ? $data['rebatecostty'] : null;
        $this->container['rebatepct'] = isset($data['rebatepct']) ? $data['rebatepct'] : null;
        $this->container['rebcalcty'] = isset($data['rebcalcty']) ? $data['rebcalcty'] : null;
        $this->container['rebdowntoty'] = isset($data['rebdowntoty']) ? $data['rebdowntoty'] : null;
        $this->container['rebateamt'] = isset($data['rebateamt']) ? $data['rebateamt'] : null;
        $this->container['contractcostfl'] = isset($data['contractcostfl']) ? $data['contractcostfl'] : null;
        $this->container['capselltypefl'] = isset($data['capselltypefl']) ? $data['capselltypefl'] : null;
        $this->container['sharefl'] = isset($data['sharefl']) ? $data['sharefl'] : null;
        $this->container['capsellamount'] = isset($data['capsellamount']) ? $data['capsellamount'] : null;
        $this->container['sharepct'] = isset($data['sharepct']) ? $data['sharepct'] : null;
        $this->container['manualfl'] = isset($data['manualfl']) ? $data['manualfl'] : null;
        $this->container['currencyty'] = isset($data['currencyty']) ? $data['currencyty'] : null;
        $this->container['caprebfl'] = isset($data['caprebfl']) ? $data['caprebfl'] : null;
        $this->container['vendprodgrp'] = isset($data['vendprodgrp']) ? $data['vendprodgrp'] : null;
        $this->container['prodpricety'] = isset($data['prodpricety']) ? $data['prodpricety'] : null;
        $this->container['prodcat'] = isset($data['prodcat']) ? $data['prodcat'] : null;
        $this->container['prodline'] = isset($data['prodline']) ? $data['prodline'] : null;
        $this->container['prodrebtype'] = isset($data['prodrebtype']) ? $data['prodrebtype'] : null;
        $this->container['rebsubty'] = isset($data['rebsubty']) ? $data['rebsubty'] : null;
        $this->container['rebrecno'] = isset($data['rebrecno']) ? $data['rebrecno'] : null;
        $this->container['usecontractlineno'] = isset($data['usecontractlineno']) ? $data['usecontractlineno'] : null;
        $this->container['errorfl'] = isset($data['errorfl']) ? $data['errorfl'] : null;
        $this->container['errortype'] = isset($data['errortype']) ? $data['errortype'] : null;
        $this->container['setid'] = isset($data['setid']) ? $data['setid'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets actiontype
     *
     * @return string
     */
    public function getActiontype()
    {
        return $this->container['actiontype'];
    }

    /**
     * Sets actiontype
     *
     * @param string $actiontype actiontype
     *
     * @return $this
     */
    public function setActiontype($actiontype)
    {
        $this->container['actiontype'] = $actiontype;

        return $this;
    }

    /**
     * Gets seqno
     *
     * @return int
     */
    public function getSeqno()
    {
        return $this->container['seqno'];
    }

    /**
     * Sets seqno
     *
     * @param int $seqno seqno
     *
     * @return $this
     */
    public function setSeqno($seqno)
    {
        $this->container['seqno'] = $seqno;

        return $this;
    }

    /**
     * Gets doctype
     *
     * @return string
     */
    public function getDoctype()
    {
        return $this->container['doctype'];
    }

    /**
     * Sets doctype
     *
     * @param string $doctype doctype
     *
     * @return $this
     */
    public function setDoctype($doctype)
    {
        $this->container['doctype'] = $doctype;

        return $this;
    }

    /**
     * Gets levelcd
     *
     * @return int
     */
    public function getLevelcd()
    {
        return $this->container['levelcd'];
    }

    /**
     * Sets levelcd
     *
     * @param int $levelcd levelcd
     *
     * @return $this
     */
    public function setLevelcd($levelcd)
    {
        $this->container['levelcd'] = $levelcd;

        return $this;
    }

    /**
     * Gets rebatecd
     *
     * @return string
     */
    public function getRebatecd()
    {
        return $this->container['rebatecd'];
    }

    /**
     * Sets rebatecd
     *
     * @param string $rebatecd rebatecd
     *
     * @return $this
     */
    public function setRebatecd($rebatecd)
    {
        $this->container['rebatecd'] = $rebatecd;

        return $this;
    }

    /**
     * Gets vendno
     *
     * @return double
     */
    public function getVendno()
    {
        return $this->container['vendno'];
    }

    /**
     * Sets vendno
     *
     * @param double $vendno vendno
     *
     * @return $this
     */
    public function setVendno($vendno)
    {
        $this->container['vendno'] = $vendno;

        return $this;
    }

    /**
     * Gets edipartner
     *
     * @return string
     */
    public function getEdipartner()
    {
        return $this->container['edipartner'];
    }

    /**
     * Sets edipartner
     *
     * @param string $edipartner edipartner
     *
     * @return $this
     */
    public function setEdipartner($edipartner)
    {
        $this->container['edipartner'] = $edipartner;

        return $this;
    }

    /**
     * Gets vendduns
     *
     * @return string
     */
    public function getVendduns()
    {
        return $this->container['vendduns'];
    }

    /**
     * Sets vendduns
     *
     * @param string $vendduns vendduns
     *
     * @return $this
     */
    public function setVendduns($vendduns)
    {
        $this->container['vendduns'] = $vendduns;

        return $this;
    }

    /**
     * Gets sendersvendid
     *
     * @return string
     */
    public function getSendersvendid()
    {
        return $this->container['sendersvendid'];
    }

    /**
     * Sets sendersvendid
     *
     * @param string $sendersvendid sendersvendid
     *
     * @return $this
     */
    public function setSendersvendid($sendersvendid)
    {
        $this->container['sendersvendid'] = $sendersvendid;

        return $this;
    }

    /**
     * Gets custno
     *
     * @return double
     */
    public function getCustno()
    {
        return $this->container['custno'];
    }

    /**
     * Sets custno
     *
     * @param double $custno custno
     *
     * @return $this
     */
    public function setCustno($custno)
    {
        $this->container['custno'] = $custno;

        return $this;
    }

    /**
     * Gets custedipartner
     *
     * @return string
     */
    public function getCustedipartner()
    {
        return $this->container['custedipartner'];
    }

    /**
     * Sets custedipartner
     *
     * @param string $custedipartner custedipartner
     *
     * @return $this
     */
    public function setCustedipartner($custedipartner)
    {
        $this->container['custedipartner'] = $custedipartner;

        return $this;
    }

    /**
     * Gets custduns
     *
     * @return string
     */
    public function getCustduns()
    {
        return $this->container['custduns'];
    }

    /**
     * Sets custduns
     *
     * @param string $custduns custduns
     *
     * @return $this
     */
    public function setCustduns($custduns)
    {
        $this->container['custduns'] = $custduns;

        return $this;
    }

    /**
     * Gets shipto
     *
     * @return string
     */
    public function getShipto()
    {
        return $this->container['shipto'];
    }

    /**
     * Sets shipto
     *
     * @param string $shipto shipto
     *
     * @return $this
     */
    public function setShipto($shipto)
    {
        $this->container['shipto'] = $shipto;

        return $this;
    }

    /**
     * Gets custrebty
     *
     * @return string
     */
    public function getCustrebty()
    {
        return $this->container['custrebty'];
    }

    /**
     * Sets custrebty
     *
     * @param string $custrebty custrebty
     *
     * @return $this
     */
    public function setCustrebty($custrebty)
    {
        $this->container['custrebty'] = $custrebty;

        return $this;
    }

    /**
     * Gets product
     *
     * @return string
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param string $product product
     *
     * @return $this
     */
    public function setProduct($product)
    {
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets vendprod
     *
     * @return string
     */
    public function getVendprod()
    {
        return $this->container['vendprod'];
    }

    /**
     * Sets vendprod
     *
     * @param string $vendprod vendprod
     *
     * @return $this
     */
    public function setVendprod($vendprod)
    {
        $this->container['vendprod'] = $vendprod;

        return $this;
    }

    /**
     * Gets barcodeprod
     *
     * @return string
     */
    public function getBarcodeprod()
    {
        return $this->container['barcodeprod'];
    }

    /**
     * Sets barcodeprod
     *
     * @param string $barcodeprod barcodeprod
     *
     * @return $this
     */
    public function setBarcodeprod($barcodeprod)
    {
        $this->container['barcodeprod'] = $barcodeprod;

        return $this;
    }

    /**
     * Gets upcsection1
     *
     * @return double
     */
    public function getUpcsection1()
    {
        return $this->container['upcsection1'];
    }

    /**
     * Sets upcsection1
     *
     * @param double $upcsection1 upcsection1
     *
     * @return $this
     */
    public function setUpcsection1($upcsection1)
    {
        $this->container['upcsection1'] = $upcsection1;

        return $this;
    }

    /**
     * Gets upcsection2
     *
     * @return double
     */
    public function getUpcsection2()
    {
        return $this->container['upcsection2'];
    }

    /**
     * Sets upcsection2
     *
     * @param double $upcsection2 upcsection2
     *
     * @return $this
     */
    public function setUpcsection2($upcsection2)
    {
        $this->container['upcsection2'] = $upcsection2;

        return $this;
    }

    /**
     * Gets upcsection3
     *
     * @return double
     */
    public function getUpcsection3()
    {
        return $this->container['upcsection3'];
    }

    /**
     * Sets upcsection3
     *
     * @param double $upcsection3 upcsection3
     *
     * @return $this
     */
    public function setUpcsection3($upcsection3)
    {
        $this->container['upcsection3'] = $upcsection3;

        return $this;
    }

    /**
     * Gets upcsection4
     *
     * @return double
     */
    public function getUpcsection4()
    {
        return $this->container['upcsection4'];
    }

    /**
     * Sets upcsection4
     *
     * @param double $upcsection4 upcsection4
     *
     * @return $this
     */
    public function setUpcsection4($upcsection4)
    {
        $this->container['upcsection4'] = $upcsection4;

        return $this;
    }

    /**
     * Gets upcsection5
     *
     * @return double
     */
    public function getUpcsection5()
    {
        return $this->container['upcsection5'];
    }

    /**
     * Sets upcsection5
     *
     * @param double $upcsection5 upcsection5
     *
     * @return $this
     */
    public function setUpcsection5($upcsection5)
    {
        $this->container['upcsection5'] = $upcsection5;

        return $this;
    }

    /**
     * Gets upcsection6
     *
     * @return double
     */
    public function getUpcsection6()
    {
        return $this->container['upcsection6'];
    }

    /**
     * Sets upcsection6
     *
     * @param double $upcsection6 upcsection6
     *
     * @return $this
     */
    public function setUpcsection6($upcsection6)
    {
        $this->container['upcsection6'] = $upcsection6;

        return $this;
    }

    /**
     * Gets upcnumber
     *
     * @return double
     */
    public function getUpcnumber()
    {
        return $this->container['upcnumber'];
    }

    /**
     * Sets upcnumber
     *
     * @param double $upcnumber upcnumber
     *
     * @return $this
     */
    public function setUpcnumber($upcnumber)
    {
        $this->container['upcnumber'] = $upcnumber;

        return $this;
    }

    /**
     * Gets naedprodcd
     *
     * @return string
     */
    public function getNaedprodcd()
    {
        return $this->container['naedprodcd'];
    }

    /**
     * Sets naedprodcd
     *
     * @param string $naedprodcd naedprodcd
     *
     * @return $this
     */
    public function setNaedprodcd($naedprodcd)
    {
        $this->container['naedprodcd'] = $naedprodcd;

        return $this;
    }

    /**
     * Gets startdt
     *
     * @return \DateTime
     */
    public function getStartdt()
    {
        return $this->container['startdt'];
    }

    /**
     * Sets startdt
     *
     * @param \DateTime $startdt startdt
     *
     * @return $this
     */
    public function setStartdt($startdt)
    {
        $this->container['startdt'] = $startdt;

        return $this;
    }

    /**
     * Gets enddt
     *
     * @return \DateTime
     */
    public function getEnddt()
    {
        return $this->container['enddt'];
    }

    /**
     * Sets enddt
     *
     * @param \DateTime $enddt enddt
     *
     * @return $this
     */
    public function setEnddt($enddt)
    {
        $this->container['enddt'] = $enddt;

        return $this;
    }

    /**
     * Gets whse
     *
     * @return string
     */
    public function getWhse()
    {
        return $this->container['whse'];
    }

    /**
     * Sets whse
     *
     * @param string $whse whse
     *
     * @return $this
     */
    public function setWhse($whse)
    {
        $this->container['whse'] = $whse;

        return $this;
    }

    /**
     * Gets whseduns
     *
     * @return string
     */
    public function getWhseduns()
    {
        return $this->container['whseduns'];
    }

    /**
     * Sets whseduns
     *
     * @param string $whseduns whseduns
     *
     * @return $this
     */
    public function setWhseduns($whseduns)
    {
        $this->container['whseduns'] = $whseduns;

        return $this;
    }

    /**
     * Gets region
     *
     * @return string
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param string $region region
     *
     * @return $this
     */
    public function setRegion($region)
    {
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets dropshipty
     *
     * @return string
     */
    public function getDropshipty()
    {
        return $this->container['dropshipty'];
    }

    /**
     * Sets dropshipty
     *
     * @param string $dropshipty dropshipty
     *
     * @return $this
     */
    public function setDropshipty($dropshipty)
    {
        $this->container['dropshipty'] = $dropshipty;

        return $this;
    }

    /**
     * Gets contractno
     *
     * @return string
     */
    public function getContractno()
    {
        return $this->container['contractno'];
    }

    /**
     * Sets contractno
     *
     * @param string $contractno contractno
     *
     * @return $this
     */
    public function setContractno($contractno)
    {
        $this->container['contractno'] = $contractno;

        return $this;
    }

    /**
     * Gets contractlineno
     *
     * @return int
     */
    public function getContractlineno()
    {
        return $this->container['contractlineno'];
    }

    /**
     * Sets contractlineno
     *
     * @param int $contractlineno contractlineno
     *
     * @return $this
     */
    public function setContractlineno($contractlineno)
    {
        $this->container['contractlineno'] = $contractlineno;

        return $this;
    }

    /**
     * Gets refer
     *
     * @return string
     */
    public function getRefer()
    {
        return $this->container['refer'];
    }

    /**
     * Sets refer
     *
     * @param string $refer refer
     *
     * @return $this
     */
    public function setRefer($refer)
    {
        $this->container['refer'] = $refer;

        return $this;
    }

    /**
     * Gets priceeffectdt
     *
     * @return \DateTime
     */
    public function getPriceeffectdt()
    {
        return $this->container['priceeffectdt'];
    }

    /**
     * Sets priceeffectdt
     *
     * @param \DateTime $priceeffectdt priceeffectdt
     *
     * @return $this
     */
    public function setPriceeffectdt($priceeffectdt)
    {
        $this->container['priceeffectdt'] = $priceeffectdt;

        return $this;
    }

    /**
     * Gets priceeffectdtto
     *
     * @return \DateTime
     */
    public function getPriceeffectdtto()
    {
        return $this->container['priceeffectdtto'];
    }

    /**
     * Sets priceeffectdtto
     *
     * @param \DateTime $priceeffectdtto priceeffectdtto
     *
     * @return $this
     */
    public function setPriceeffectdtto($priceeffectdtto)
    {
        $this->container['priceeffectdtto'] = $priceeffectdtto;

        return $this;
    }

    /**
     * Gets pricesheet
     *
     * @return string
     */
    public function getPricesheet()
    {
        return $this->container['pricesheet'];
    }

    /**
     * Sets pricesheet
     *
     * @param string $pricesheet pricesheet
     *
     * @return $this
     */
    public function setPricesheet($pricesheet)
    {
        $this->container['pricesheet'] = $pricesheet;

        return $this;
    }

    /**
     * Gets pricesheetto
     *
     * @return string
     */
    public function getPricesheetto()
    {
        return $this->container['pricesheetto'];
    }

    /**
     * Sets pricesheetto
     *
     * @param string $pricesheetto pricesheetto
     *
     * @return $this
     */
    public function setPricesheetto($pricesheetto)
    {
        $this->container['pricesheetto'] = $pricesheetto;

        return $this;
    }

    /**
     * Gets margincostty
     *
     * @return string
     */
    public function getMargincostty()
    {
        return $this->container['margincostty'];
    }

    /**
     * Sets margincostty
     *
     * @param string $margincostty margincostty
     *
     * @return $this
     */
    public function setMargincostty($margincostty)
    {
        $this->container['margincostty'] = $margincostty;

        return $this;
    }

    /**
     * Gets rebatecostty
     *
     * @return string
     */
    public function getRebatecostty()
    {
        return $this->container['rebatecostty'];
    }

    /**
     * Sets rebatecostty
     *
     * @param string $rebatecostty rebatecostty
     *
     * @return $this
     */
    public function setRebatecostty($rebatecostty)
    {
        $this->container['rebatecostty'] = $rebatecostty;

        return $this;
    }

    /**
     * Gets rebatepct
     *
     * @return double
     */
    public function getRebatepct()
    {
        return $this->container['rebatepct'];
    }

    /**
     * Sets rebatepct
     *
     * @param double $rebatepct rebatepct
     *
     * @return $this
     */
    public function setRebatepct($rebatepct)
    {
        $this->container['rebatepct'] = $rebatepct;

        return $this;
    }

    /**
     * Gets rebcalcty
     *
     * @return string
     */
    public function getRebcalcty()
    {
        return $this->container['rebcalcty'];
    }

    /**
     * Sets rebcalcty
     *
     * @param string $rebcalcty rebcalcty
     *
     * @return $this
     */
    public function setRebcalcty($rebcalcty)
    {
        $this->container['rebcalcty'] = $rebcalcty;

        return $this;
    }

    /**
     * Gets rebdowntoty
     *
     * @return string
     */
    public function getRebdowntoty()
    {
        return $this->container['rebdowntoty'];
    }

    /**
     * Sets rebdowntoty
     *
     * @param string $rebdowntoty rebdowntoty
     *
     * @return $this
     */
    public function setRebdowntoty($rebdowntoty)
    {
        $this->container['rebdowntoty'] = $rebdowntoty;

        return $this;
    }

    /**
     * Gets rebateamt
     *
     * @return double
     */
    public function getRebateamt()
    {
        return $this->container['rebateamt'];
    }

    /**
     * Sets rebateamt
     *
     * @param double $rebateamt rebateamt
     *
     * @return $this
     */
    public function setRebateamt($rebateamt)
    {
        $this->container['rebateamt'] = $rebateamt;

        return $this;
    }

    /**
     * Gets contractcostfl
     *
     * @return bool
     */
    public function getContractcostfl()
    {
        return $this->container['contractcostfl'];
    }

    /**
     * Sets contractcostfl
     *
     * @param bool $contractcostfl contractcostfl
     *
     * @return $this
     */
    public function setContractcostfl($contractcostfl)
    {
        $this->container['contractcostfl'] = $contractcostfl;

        return $this;
    }

    /**
     * Gets capselltypefl
     *
     * @return bool
     */
    public function getCapselltypefl()
    {
        return $this->container['capselltypefl'];
    }

    /**
     * Sets capselltypefl
     *
     * @param bool $capselltypefl capselltypefl
     *
     * @return $this
     */
    public function setCapselltypefl($capselltypefl)
    {
        $this->container['capselltypefl'] = $capselltypefl;

        return $this;
    }

    /**
     * Gets sharefl
     *
     * @return bool
     */
    public function getSharefl()
    {
        return $this->container['sharefl'];
    }

    /**
     * Sets sharefl
     *
     * @param bool $sharefl sharefl
     *
     * @return $this
     */
    public function setSharefl($sharefl)
    {
        $this->container['sharefl'] = $sharefl;

        return $this;
    }

    /**
     * Gets capsellamount
     *
     * @return double
     */
    public function getCapsellamount()
    {
        return $this->container['capsellamount'];
    }

    /**
     * Sets capsellamount
     *
     * @param double $capsellamount capsellamount
     *
     * @return $this
     */
    public function setCapsellamount($capsellamount)
    {
        $this->container['capsellamount'] = $capsellamount;

        return $this;
    }

    /**
     * Gets sharepct
     *
     * @return double
     */
    public function getSharepct()
    {
        return $this->container['sharepct'];
    }

    /**
     * Sets sharepct
     *
     * @param double $sharepct sharepct
     *
     * @return $this
     */
    public function setSharepct($sharepct)
    {
        $this->container['sharepct'] = $sharepct;

        return $this;
    }

    /**
     * Gets manualfl
     *
     * @return bool
     */
    public function getManualfl()
    {
        return $this->container['manualfl'];
    }

    /**
     * Sets manualfl
     *
     * @param bool $manualfl manualfl
     *
     * @return $this
     */
    public function setManualfl($manualfl)
    {
        $this->container['manualfl'] = $manualfl;

        return $this;
    }

    /**
     * Gets currencyty
     *
     * @return string
     */
    public function getCurrencyty()
    {
        return $this->container['currencyty'];
    }

    /**
     * Sets currencyty
     *
     * @param string $currencyty currencyty
     *
     * @return $this
     */
    public function setCurrencyty($currencyty)
    {
        $this->container['currencyty'] = $currencyty;

        return $this;
    }

    /**
     * Gets caprebfl
     *
     * @return bool
     */
    public function getCaprebfl()
    {
        return $this->container['caprebfl'];
    }

    /**
     * Sets caprebfl
     *
     * @param bool $caprebfl caprebfl
     *
     * @return $this
     */
    public function setCaprebfl($caprebfl)
    {
        $this->container['caprebfl'] = $caprebfl;

        return $this;
    }

    /**
     * Gets vendprodgrp
     *
     * @return string
     */
    public function getVendprodgrp()
    {
        return $this->container['vendprodgrp'];
    }

    /**
     * Sets vendprodgrp
     *
     * @param string $vendprodgrp vendprodgrp
     *
     * @return $this
     */
    public function setVendprodgrp($vendprodgrp)
    {
        $this->container['vendprodgrp'] = $vendprodgrp;

        return $this;
    }

    /**
     * Gets prodpricety
     *
     * @return string
     */
    public function getProdpricety()
    {
        return $this->container['prodpricety'];
    }

    /**
     * Sets prodpricety
     *
     * @param string $prodpricety prodpricety
     *
     * @return $this
     */
    public function setProdpricety($prodpricety)
    {
        $this->container['prodpricety'] = $prodpricety;

        return $this;
    }

    /**
     * Gets prodcat
     *
     * @return string
     */
    public function getProdcat()
    {
        return $this->container['prodcat'];
    }

    /**
     * Sets prodcat
     *
     * @param string $prodcat prodcat
     *
     * @return $this
     */
    public function setProdcat($prodcat)
    {
        $this->container['prodcat'] = $prodcat;

        return $this;
    }

    /**
     * Gets prodline
     *
     * @return string
     */
    public function getProdline()
    {
        return $this->container['prodline'];
    }

    /**
     * Sets prodline
     *
     * @param string $prodline prodline
     *
     * @return $this
     */
    public function setProdline($prodline)
    {
        $this->container['prodline'] = $prodline;

        return $this;
    }

    /**
     * Gets prodrebtype
     *
     * @return string
     */
    public function getProdrebtype()
    {
        return $this->container['prodrebtype'];
    }

    /**
     * Sets prodrebtype
     *
     * @param string $prodrebtype prodrebtype
     *
     * @return $this
     */
    public function setProdrebtype($prodrebtype)
    {
        $this->container['prodrebtype'] = $prodrebtype;

        return $this;
    }

    /**
     * Gets rebsubty
     *
     * @return string
     */
    public function getRebsubty()
    {
        return $this->container['rebsubty'];
    }

    /**
     * Sets rebsubty
     *
     * @param string $rebsubty rebsubty
     *
     * @return $this
     */
    public function setRebsubty($rebsubty)
    {
        $this->container['rebsubty'] = $rebsubty;

        return $this;
    }

    /**
     * Gets rebrecno
     *
     * @return int
     */
    public function getRebrecno()
    {
        return $this->container['rebrecno'];
    }

    /**
     * Sets rebrecno
     *
     * @param int $rebrecno rebrecno
     *
     * @return $this
     */
    public function setRebrecno($rebrecno)
    {
        $this->container['rebrecno'] = $rebrecno;

        return $this;
    }

    /**
     * Gets usecontractlineno
     *
     * @return bool
     */
    public function getUsecontractlineno()
    {
        return $this->container['usecontractlineno'];
    }

    /**
     * Sets usecontractlineno
     *
     * @param bool $usecontractlineno usecontractlineno
     *
     * @return $this
     */
    public function setUsecontractlineno($usecontractlineno)
    {
        $this->container['usecontractlineno'] = $usecontractlineno;

        return $this;
    }

    /**
     * Gets errorfl
     *
     * @return bool
     */
    public function getErrorfl()
    {
        return $this->container['errorfl'];
    }

    /**
     * Sets errorfl
     *
     * @param bool $errorfl errorfl
     *
     * @return $this
     */
    public function setErrorfl($errorfl)
    {
        $this->container['errorfl'] = $errorfl;

        return $this;
    }

    /**
     * Gets errortype
     *
     * @return string
     */
    public function getErrortype()
    {
        return $this->container['errortype'];
    }

    /**
     * Sets errortype
     *
     * @param string $errortype errortype
     *
     * @return $this
     */
    public function setErrortype($errortype)
    {
        $this->container['errortype'] = $errortype;

        return $this;
    }

    /**
     * Gets setid
     *
     * @return string
     */
    public function getSetid()
    {
        return $this->container['setid'];
    }

    /**
     * Sets setid
     *
     * @param string $setid setid
     *
     * @return $this
     */
    public function setSetid($setid)
    {
        $this->container['setid'] = $setid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


