<?php
/**
 * SxapiicgetprodcrossreferencelistRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SxapiicgetprodcrossreferencelistRequestTest Class Doc Comment
 *
 * @category    Class
 * @description SxapiicgetprodcrossreferencelistRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SxapiicgetprodcrossreferencelistRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SxapiicgetprodcrossreferencelistRequest"
     */
    public function testSxapiicgetprodcrossreferencelistRequest()
    {
    }

    /**
     * Test attribute "company_number"
     */
    public function testPropertyCompanyNumber()
    {
    }

    /**
     * Test attribute "operator_init"
     */
    public function testPropertyOperatorInit()
    {
    }

    /**
     * Test attribute "operator_password"
     */
    public function testPropertyOperatorPassword()
    {
    }

    /**
     * Test attribute "record_types"
     */
    public function testPropertyRecordTypes()
    {
    }

    /**
     * Test attribute "product_code"
     */
    public function testPropertyProductCode()
    {
    }

    /**
     * Test attribute "warehouse"
     */
    public function testPropertyWarehouse()
    {
    }

    /**
     * Test attribute "customer_number"
     */
    public function testPropertyCustomerNumber()
    {
    }

    /**
     * Test attribute "vendor_number"
     */
    public function testPropertyVendorNumber()
    {
    }

    /**
     * Test attribute "record_limit"
     */
    public function testPropertyRecordLimit()
    {
    }
}
