<?php
/**
 * SxapisfgetoeorderdataRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SxapisfgetoeorderdataRequestTest Class Doc Comment
 *
 * @category    Class
 * @description SxapisfgetoeorderdataRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SxapisfgetoeorderdataRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SxapisfgetoeorderdataRequest"
     */
    public function testSxapisfgetoeorderdataRequest()
    {
    }

    /**
     * Test attribute "company_number"
     */
    public function testPropertyCompanyNumber()
    {
    }

    /**
     * Test attribute "operator_init"
     */
    public function testPropertyOperatorInit()
    {
    }

    /**
     * Test attribute "operator_password"
     */
    public function testPropertyOperatorPassword()
    {
    }

    /**
     * Test attribute "get_order_info"
     */
    public function testPropertyGetOrderInfo()
    {
    }

    /**
     * Test attribute "customer_number"
     */
    public function testPropertyCustomerNumber()
    {
    }

    /**
     * Test attribute "lookup_type"
     */
    public function testPropertyLookupType()
    {
    }

    /**
     * Test attribute "source_type"
     */
    public function testPropertySourceType()
    {
    }

    /**
     * Test attribute "from_entry_date"
     */
    public function testPropertyFromEntryDate()
    {
    }

    /**
     * Test attribute "to_entry_date"
     */
    public function testPropertyToEntryDate()
    {
    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {
    }

    /**
     * Test attribute "order_suffix"
     */
    public function testPropertyOrderSuffix()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "customer_purchase_order_number"
     */
    public function testPropertyCustomerPurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "parent_order_number"
     */
    public function testPropertyParentOrderNumber()
    {
    }

    /**
     * Test attribute "guest_flag"
     */
    public function testPropertyGuestFlag()
    {
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "history_sequence_number"
     */
    public function testPropertyHistorySequenceNumber()
    {
    }

    /**
     * Test attribute "entry_date"
     */
    public function testPropertyEntryDate()
    {
    }
}
