<?php
/**
 * SxapiicgetwarehousedatageneralResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SxapiicgetwarehousedatageneralResponseTest Class Doc Comment
 *
 * @category    Class
 * @description SxapiicgetwarehousedatageneralResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SxapiicgetwarehousedatageneralResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SxapiicgetwarehousedatageneralResponse"
     */
    public function testSxapiicgetwarehousedatageneralResponse()
    {
    }

    /**
     * Test attribute "c_error_message"
     */
    public function testPropertyCErrorMessage()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "address1"
     */
    public function testPropertyAddress1()
    {
    }

    /**
     * Test attribute "address2"
     */
    public function testPropertyAddress2()
    {
    }

    /**
     * Test attribute "address3"
     */
    public function testPropertyAddress3()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "managed_flag"
     */
    public function testPropertyManagedFlag()
    {
    }

    /**
     * Test attribute "customer_number"
     */
    public function testPropertyCustomerNumber()
    {
    }

    /**
     * Test attribute "ship_to"
     */
    public function testPropertyShipTo()
    {
    }

    /**
     * Test attribute "printer_name"
     */
    public function testPropertyPrinterName()
    {
    }

    /**
     * Test attribute "cycle_count_show_expected_flag"
     */
    public function testPropertyCycleCountShowExpectedFlag()
    {
    }

    /**
     * Test attribute "phys_inv_show_expected_flag"
     */
    public function testPropertyPhysInvShowExpectedFlag()
    {
    }

    /**
     * Test attribute "auto_receive_wt_flag"
     */
    public function testPropertyAutoReceiveWtFlag()
    {
    }
}
