<?php
/**
 * SxapikpgetlistofworkordersRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SxapikpgetlistofworkordersRequestTest Class Doc Comment
 *
 * @category    Class
 * @description SxapikpgetlistofworkordersRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SxapikpgetlistofworkordersRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SxapikpgetlistofworkordersRequest"
     */
    public function testSxapikpgetlistofworkordersRequest()
    {
    }

    /**
     * Test attribute "company_number"
     */
    public function testPropertyCompanyNumber()
    {
    }

    /**
     * Test attribute "operator_init"
     */
    public function testPropertyOperatorInit()
    {
    }

    /**
     * Test attribute "operator_password"
     */
    public function testPropertyOperatorPassword()
    {
    }

    /**
     * Test attribute "kit_product_code"
     */
    public function testPropertyKitProductCode()
    {
    }

    /**
     * Test attribute "component_product_code"
     */
    public function testPropertyComponentProductCode()
    {
    }

    /**
     * Test attribute "warehouse"
     */
    public function testPropertyWarehouse()
    {
    }

    /**
     * Test attribute "beginning_stage_code"
     */
    public function testPropertyBeginningStageCode()
    {
    }

    /**
     * Test attribute "ending_stage_code"
     */
    public function testPropertyEndingStageCode()
    {
    }

    /**
     * Test attribute "beginning_entered_date"
     */
    public function testPropertyBeginningEnteredDate()
    {
    }

    /**
     * Test attribute "ending_entered_date"
     */
    public function testPropertyEndingEnteredDate()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "status_type"
     */
    public function testPropertyStatusType()
    {
    }

    /**
     * Test attribute "backorder_only_flag"
     */
    public function testPropertyBackorderOnlyFlag()
    {
    }

    /**
     * Test attribute "sort1"
     */
    public function testPropertySort1()
    {
    }

    /**
     * Test attribute "sort2"
     */
    public function testPropertySort2()
    {
    }

    /**
     * Test attribute "record_limit"
     */
    public function testPropertyRecordLimit()
    {
    }

    /**
     * Test attribute "t_infieldvalue"
     */
    public function testPropertyTInfieldvalue()
    {
    }
}
