<?php
/**
 * Sxapioepricingv3ResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Sxapioepricingv3ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Sxapioepricingv3Response
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Sxapioepricingv3ResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Sxapioepricingv3Response"
     */
    public function testSxapioepricingv3Response()
    {
    }

    /**
     * Test attribute "c_error_message"
     */
    public function testPropertyCErrorMessage()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "discount_amount"
     */
    public function testPropertyDiscountAmount()
    {
    }

    /**
     * Test attribute "discount_type"
     */
    public function testPropertyDiscountType()
    {
    }

    /**
     * Test attribute "net_available"
     */
    public function testPropertyNetAvailable()
    {
    }

    /**
     * Test attribute "special_cost_type"
     */
    public function testPropertySpecialCostType()
    {
    }

    /**
     * Test attribute "price_cost_per"
     */
    public function testPropertyPriceCostPer()
    {
    }

    /**
     * Test attribute "units_per_stocking"
     */
    public function testPropertyUnitsPerStocking()
    {
    }

    /**
     * Test attribute "special_conversion"
     */
    public function testPropertySpecialConversion()
    {
    }

    /**
     * Test attribute "special_cost_record_number"
     */
    public function testPropertySpecialCostRecordNumber()
    {
    }

    /**
     * Test attribute "stocking_quantity_ordered"
     */
    public function testPropertyStockingQuantityOrdered()
    {
    }

    /**
     * Test attribute "unit_conversion"
     */
    public function testPropertyUnitConversion()
    {
    }

    /**
     * Test attribute "pricing_record_number"
     */
    public function testPropertyPricingRecordNumber()
    {
    }

    /**
     * Test attribute "promotional_flag"
     */
    public function testPropertyPromotionalFlag()
    {
    }

    /**
     * Test attribute "price_origin_code"
     */
    public function testPropertyPriceOriginCode()
    {
    }

    /**
     * Test attribute "units_per_stocking_text"
     */
    public function testPropertyUnitsPerStockingText()
    {
    }

    /**
     * Test attribute "extended_amount"
     */
    public function testPropertyExtendedAmount()
    {
    }

    /**
     * Test attribute "extended_discount_amount"
     */
    public function testPropertyExtendedDiscountAmount()
    {
    }
}
