<?php
/**
 * TIcprodwhsedataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TIcprodwhsedataTest Class Doc Comment
 *
 * @category    Class
 * @description TIcprodwhsedata
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TIcprodwhsedataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TIcprodwhsedata"
     */
    public function testTIcprodwhsedata()
    {
    }

    /**
     * Test attribute "prod"
     */
    public function testPropertyProd()
    {
    }

    /**
     * Test attribute "whse"
     */
    public function testPropertyWhse()
    {
    }

    /**
     * Test attribute "statustype"
     */
    public function testPropertyStatustype()
    {
    }

    /**
     * Test attribute "nonstockty"
     */
    public function testPropertyNonstockty()
    {
    }

    /**
     * Test attribute "serlottype"
     */
    public function testPropertySerlottype()
    {
    }

    /**
     * Test attribute "reservety"
     */
    public function testPropertyReservety()
    {
    }

    /**
     * Test attribute "reservedays"
     */
    public function testPropertyReservedays()
    {
    }

    /**
     * Test attribute "pricetype"
     */
    public function testPropertyPricetype()
    {
    }

    /**
     * Test attribute "pricetypedesc"
     */
    public function testPropertyPricetypedesc()
    {
    }

    /**
     * Test attribute "prodline"
     */
    public function testPropertyProdline()
    {
    }

    /**
     * Test attribute "baseprice"
     */
    public function testPropertyBaseprice()
    {
    }

    /**
     * Test attribute "listprice"
     */
    public function testPropertyListprice()
    {
    }

    /**
     * Test attribute "arptype"
     */
    public function testPropertyArptype()
    {
    }

    /**
     * Test attribute "arpvendno"
     */
    public function testPropertyArpvendno()
    {
    }

    /**
     * Test attribute "arpwhse"
     */
    public function testPropertyArpwhse()
    {
    }

    /**
     * Test attribute "binloc1"
     */
    public function testPropertyBinloc1()
    {
    }

    /**
     * Test attribute "binloc2"
     */
    public function testPropertyBinloc2()
    {
    }

    /**
     * Test attribute "leadtmavg"
     */
    public function testPropertyLeadtmavg()
    {
    }

    /**
     * Test attribute "arppushfl"
     */
    public function testPropertyArppushfl()
    {
    }

    /**
     * Test attribute "bintype"
     */
    public function testPropertyBintype()
    {
    }

    /**
     * Test attribute "boshortfl"
     */
    public function testPropertyBoshortfl()
    {
    }

    /**
     * Test attribute "enterdt"
     */
    public function testPropertyEnterdt()
    {
    }

    /**
     * Test attribute "famgrptype"
     */
    public function testPropertyFamgrptype()
    {
    }

    /**
     * Test attribute "frtextra1"
     */
    public function testPropertyFrtextra1()
    {
    }

    /**
     * Test attribute "frtextra2"
     */
    public function testPropertyFrtextra2()
    {
    }

    /**
     * Test attribute "frtfreefl"
     */
    public function testPropertyFrtfreefl()
    {
    }

    /**
     * Test attribute "lastpowtdt"
     */
    public function testPropertyLastpowtdt()
    {
    }

    /**
     * Test attribute "vendprod"
     */
    public function testPropertyVendprod()
    {
    }

    /**
     * Test attribute "lastupdate"
     */
    public function testPropertyLastupdate()
    {
    }

    /**
     * Test attribute "acquiredt"
     */
    public function testPropertyAcquiredt()
    {
    }

    /**
     * Test attribute "user1"
     */
    public function testPropertyUser1()
    {
    }

    /**
     * Test attribute "user2"
     */
    public function testPropertyUser2()
    {
    }

    /**
     * Test attribute "user3"
     */
    public function testPropertyUser3()
    {
    }

    /**
     * Test attribute "user4"
     */
    public function testPropertyUser4()
    {
    }

    /**
     * Test attribute "user5"
     */
    public function testPropertyUser5()
    {
    }

    /**
     * Test attribute "user6"
     */
    public function testPropertyUser6()
    {
    }

    /**
     * Test attribute "user7"
     */
    public function testPropertyUser7()
    {
    }

    /**
     * Test attribute "user8"
     */
    public function testPropertyUser8()
    {
    }

    /**
     * Test attribute "user9"
     */
    public function testPropertyUser9()
    {
    }
}
