<?php
/**
 * TIcswusageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TIcswusageTest Class Doc Comment
 *
 * @category    Class
 * @description TIcswusage
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TIcswusageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TIcswusage"
     */
    public function testTIcswusage()
    {
    }

    /**
     * Test attribute "monthseq"
     */
    public function testPropertyMonthseq()
    {
    }

    /**
     * Test attribute "monthwords"
     */
    public function testPropertyMonthwords()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "normusage"
     */
    public function testPropertyNormusage()
    {
    }

    /**
     * Test attribute "overreasty"
     */
    public function testPropertyOverreasty()
    {
    }

    /**
     * Test attribute "overrsdesc"
     */
    public function testPropertyOverrsdesc()
    {
    }

    /**
     * Test attribute "nodaysso"
     */
    public function testPropertyNodaysso()
    {
    }

    /**
     * Test attribute "notimesso"
     */
    public function testPropertyNotimesso()
    {
    }

    /**
     * Test attribute "avginvval"
     */
    public function testPropertyAvginvval()
    {
    }

    /**
     * Test attribute "overusage"
     */
    public function testPropertyOverusage()
    {
    }

    /**
     * Test attribute "transpct"
     */
    public function testPropertyTranspct()
    {
    }

    /**
     * Test attribute "linehits"
     */
    public function testPropertyLinehits()
    {
    }

    /**
     * Test attribute "linehitswt"
     */
    public function testPropertyLinehitswt()
    {
    }

    /**
     * Test attribute "linehitslb"
     */
    public function testPropertyLinehitslb()
    {
    }

    /**
     * Test attribute "linehitstot"
     */
    public function testPropertyLinehitstot()
    {
    }
}
