<?php
/**
 * TIneqheaderdataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TIneqheaderdataTest Class Doc Comment
 *
 * @category    Class
 * @description TIneqheaderdata
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TIneqheaderdataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TIneqheaderdata"
     */
    public function testTIneqheaderdata()
    {
    }

    /**
     * Test attribute "warehouseid"
     */
    public function testPropertyWarehouseid()
    {
    }

    /**
     * Test attribute "customerid"
     */
    public function testPropertyCustomerid()
    {
    }

    /**
     * Test attribute "shiptonumber"
     */
    public function testPropertyShiptonumber()
    {
    }

    /**
     * Test attribute "unittype"
     */
    public function testPropertyUnittype()
    {
    }

    /**
     * Test attribute "currenttotal"
     */
    public function testPropertyCurrenttotal()
    {
    }

    /**
     * Test attribute "userfield"
     */
    public function testPropertyUserfield()
    {
    }
}
