<?php
/**
 * TIngenLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TIngenLineTest Class Doc Comment
 *
 * @category    Class
 * @description TIngenLine
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TIngenLineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TIngenLine"
     */
    public function testTIngenLine()
    {
    }

    /**
     * Test attribute "key1"
     */
    public function testPropertyKey1()
    {
    }

    /**
     * Test attribute "key2"
     */
    public function testPropertyKey2()
    {
    }

    /**
     * Test attribute "key3"
     */
    public function testPropertyKey3()
    {
    }

    /**
     * Test attribute "key4"
     */
    public function testPropertyKey4()
    {
    }

    /**
     * Test attribute "custno"
     */
    public function testPropertyCustno()
    {
    }

    /**
     * Test attribute "enterdt"
     */
    public function testPropertyEnterdt()
    {
    }

    /**
     * Test attribute "orderno"
     */
    public function testPropertyOrderno()
    {
    }

    /**
     * Test attribute "ordersuf"
     */
    public function testPropertyOrdersuf()
    {
    }

    /**
     * Test attribute "lineno"
     */
    public function testPropertyLineno()
    {
    }

    /**
     * Test attribute "netamt"
     */
    public function testPropertyNetamt()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "prod"
     */
    public function testPropertyProd()
    {
    }

    /**
     * Test attribute "qtyord"
     */
    public function testPropertyQtyord()
    {
    }

    /**
     * Test attribute "qtyship"
     */
    public function testPropertyQtyship()
    {
    }

    /**
     * Test attribute "shipfm"
     */
    public function testPropertyShipfm()
    {
    }

    /**
     * Test attribute "shipto"
     */
    public function testPropertyShipto()
    {
    }

    /**
     * Test attribute "statustype"
     */
    public function testPropertyStatustype()
    {
    }

    /**
     * Test attribute "vendno"
     */
    public function testPropertyVendno()
    {
    }

    /**
     * Test attribute "char1"
     */
    public function testPropertyChar1()
    {
    }

    /**
     * Test attribute "char2"
     */
    public function testPropertyChar2()
    {
    }

    /**
     * Test attribute "char3"
     */
    public function testPropertyChar3()
    {
    }

    /**
     * Test attribute "char4"
     */
    public function testPropertyChar4()
    {
    }

    /**
     * Test attribute "char5"
     */
    public function testPropertyChar5()
    {
    }

    /**
     * Test attribute "char6"
     */
    public function testPropertyChar6()
    {
    }

    /**
     * Test attribute "char7"
     */
    public function testPropertyChar7()
    {
    }

    /**
     * Test attribute "char8"
     */
    public function testPropertyChar8()
    {
    }

    /**
     * Test attribute "char9"
     */
    public function testPropertyChar9()
    {
    }

    /**
     * Test attribute "char10"
     */
    public function testPropertyChar10()
    {
    }

    /**
     * Test attribute "dec1"
     */
    public function testPropertyDec1()
    {
    }

    /**
     * Test attribute "dec2"
     */
    public function testPropertyDec2()
    {
    }

    /**
     * Test attribute "dec3"
     */
    public function testPropertyDec3()
    {
    }

    /**
     * Test attribute "dec4"
     */
    public function testPropertyDec4()
    {
    }

    /**
     * Test attribute "dec5"
     */
    public function testPropertyDec5()
    {
    }

    /**
     * Test attribute "date1"
     */
    public function testPropertyDate1()
    {
    }

    /**
     * Test attribute "date2"
     */
    public function testPropertyDate2()
    {
    }

    /**
     * Test attribute "date3"
     */
    public function testPropertyDate3()
    {
    }

    /**
     * Test attribute "date4"
     */
    public function testPropertyDate4()
    {
    }

    /**
     * Test attribute "date5"
     */
    public function testPropertyDate5()
    {
    }
}
