<?php
/**
 * TInpoackheaderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TInpoackheaderTest Class Doc Comment
 *
 * @category    Class
 * @description TInpoackheader
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TInpoackheaderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TInpoackheader"
     */
    public function testTInpoackheader()
    {
    }

    /**
     * Test attribute "ackty"
     */
    public function testPropertyAckty()
    {
    }

    /**
     * Test attribute "duedt"
     */
    public function testPropertyDuedt()
    {
    }

    /**
     * Test attribute "dunsno"
     */
    public function testPropertyDunsno()
    {
    }

    /**
     * Test attribute "edipartner"
     */
    public function testPropertyEdipartner()
    {
    }

    /**
     * Test attribute "expshipdt"
     */
    public function testPropertyExpshipdt()
    {
    }

    /**
     * Test attribute "orderdt"
     */
    public function testPropertyOrderdt()
    {
    }

    /**
     * Test attribute "porcvddt"
     */
    public function testPropertyPorcvddt()
    {
    }

    /**
     * Test attribute "vendno"
     */
    public function testPropertyVendno()
    {
    }

    /**
     * Test attribute "whse"
     */
    public function testPropertyWhse()
    {
    }

    /**
     * Test attribute "user1"
     */
    public function testPropertyUser1()
    {
    }

    /**
     * Test attribute "user2"
     */
    public function testPropertyUser2()
    {
    }

    /**
     * Test attribute "user3"
     */
    public function testPropertyUser3()
    {
    }

    /**
     * Test attribute "user4"
     */
    public function testPropertyUser4()
    {
    }

    /**
     * Test attribute "user5"
     */
    public function testPropertyUser5()
    {
    }

    /**
     * Test attribute "user6"
     */
    public function testPropertyUser6()
    {
    }

    /**
     * Test attribute "user7"
     */
    public function testPropertyUser7()
    {
    }

    /**
     * Test attribute "user8"
     */
    public function testPropertyUser8()
    {
    }

    /**
     * Test attribute "user9"
     */
    public function testPropertyUser9()
    {
    }
}
