<?php
/**
 * TOeordV4Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TOeordV4Test Class Doc Comment
 *
 * @category    Class
 * @description TOeordV4
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TOeordV4Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TOeordV4"
     */
    public function testTOeordV4()
    {
    }

    /**
     * Test attribute "order_no"
     */
    public function testPropertyOrderNo()
    {
    }

    /**
     * Test attribute "order_suf"
     */
    public function testPropertyOrderSuf()
    {
    }

    /**
     * Test attribute "whse"
     */
    public function testPropertyWhse()
    {
    }

    /**
     * Test attribute "cust_no"
     */
    public function testPropertyCustNo()
    {
    }

    /**
     * Test attribute "ship_to"
     */
    public function testPropertyShipTo()
    {
    }

    /**
     * Test attribute "stage_cd"
     */
    public function testPropertyStageCd()
    {
    }

    /**
     * Test attribute "stage_cd_words"
     */
    public function testPropertyStageCdWords()
    {
    }

    /**
     * Test attribute "enter_dt"
     */
    public function testPropertyEnterDt()
    {
    }

    /**
     * Test attribute "tot_inv_amt"
     */
    public function testPropertyTotInvAmt()
    {
    }

    /**
     * Test attribute "trans_type"
     */
    public function testPropertyTransType()
    {
    }

    /**
     * Test attribute "cust_po"
     */
    public function testPropertyCustPo()
    {
    }

    /**
     * Test attribute "req_ship_dt"
     */
    public function testPropertyReqShipDt()
    {
    }

    /**
     * Test attribute "promise_dt"
     */
    public function testPropertyPromiseDt()
    {
    }

    /**
     * Test attribute "picked_dt"
     */
    public function testPropertyPickedDt()
    {
    }

    /**
     * Test attribute "ship_dt"
     */
    public function testPropertyShipDt()
    {
    }

    /**
     * Test attribute "invoice_dt"
     */
    public function testPropertyInvoiceDt()
    {
    }

    /**
     * Test attribute "sort_fld"
     */
    public function testPropertySortFld()
    {
    }

    /**
     * Test attribute "approvty"
     */
    public function testPropertyApprovty()
    {
    }

    /**
     * Test attribute "pickedtm"
     */
    public function testPropertyPickedtm()
    {
    }

    /**
     * Test attribute "pickinit"
     */
    public function testPropertyPickinit()
    {
    }

    /**
     * Test attribute "taken_by"
     */
    public function testPropertyTakenBy()
    {
    }

    /**
     * Test attribute "tot_line_ord"
     */
    public function testPropertyTotLineOrd()
    {
    }

    /**
     * Test attribute "tot_line_amt"
     */
    public function testPropertyTotLineAmt()
    {
    }

    /**
     * Test attribute "shiptonm"
     */
    public function testPropertyShiptonm()
    {
    }

    /**
     * Test attribute "shiptost"
     */
    public function testPropertyShiptost()
    {
    }

    /**
     * Test attribute "shiptozip"
     */
    public function testPropertyShiptozip()
    {
    }

    /**
     * Test attribute "shiptoaddr1"
     */
    public function testPropertyShiptoaddr1()
    {
    }

    /**
     * Test attribute "shiptoaddr2"
     */
    public function testPropertyShiptoaddr2()
    {
    }

    /**
     * Test attribute "shiptocity"
     */
    public function testPropertyShiptocity()
    {
    }

    /**
     * Test attribute "shipviaty"
     */
    public function testPropertyShipviaty()
    {
    }

    /**
     * Test attribute "shipviadesc"
     */
    public function testPropertyShipviadesc()
    {
    }

    /**
     * Test attribute "route"
     */
    public function testPropertyRoute()
    {
    }

    /**
     * Test attribute "totcubes"
     */
    public function testPropertyTotcubes()
    {
    }

    /**
     * Test attribute "totweight"
     */
    public function testPropertyTotweight()
    {
    }

    /**
     * Test attribute "refer"
     */
    public function testPropertyRefer()
    {
    }

    /**
     * Test attribute "nolineitem"
     */
    public function testPropertyNolineitem()
    {
    }

    /**
     * Test attribute "totqtyord"
     */
    public function testPropertyTotqtyord()
    {
    }

    /**
     * Test attribute "totqtyshp"
     */
    public function testPropertyTotqtyshp()
    {
    }

    /**
     * Test attribute "custname"
     */
    public function testPropertyCustname()
    {
    }

    /**
     * Test attribute "cod_amount"
     */
    public function testPropertyCodAmount()
    {
    }

    /**
     * Test attribute "cod_flag"
     */
    public function testPropertyCodFlag()
    {
    }
}
