<?php
/**
 * TSkuchangeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TSkuchangeTest Class Doc Comment
 *
 * @category    Class
 * @description TSkuchange
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TSkuchangeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TSkuchange"
     */
    public function testTSkuchange()
    {
    }

    /**
     * Test attribute "cono"
     */
    public function testPropertyCono()
    {
    }

    /**
     * Test attribute "origprod"
     */
    public function testPropertyOrigprod()
    {
    }

    /**
     * Test attribute "newprod"
     */
    public function testPropertyNewprod()
    {
    }

    /**
     * Test attribute "extradata"
     */
    public function testPropertyExtradata()
    {
    }
}
