<?php
/**
 * TtShopListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TtShopListTest Class Doc Comment
 *
 * @category    Class
 * @description TtShopList
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TtShopListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TtShopList"
     */
    public function testTtShopList()
    {
    }

    /**
     * Test attribute "addswoptprodfl"
     */
    public function testPropertyAddswoptprodfl()
    {
    }

    /**
     * Test attribute "arpprodline"
     */
    public function testPropertyArpprodline()
    {
    }

    /**
     * Test attribute "arpvendno"
     */
    public function testPropertyArpvendno()
    {
    }

    /**
     * Test attribute "chrg"
     */
    public function testPropertyChrg()
    {
    }

    /**
     * Test attribute "cono"
     */
    public function testPropertyCono()
    {
    }

    /**
     * Test attribute "csunperstk"
     */
    public function testPropertyCsunperstk()
    {
    }

    /**
     * Test attribute "cubes"
     */
    public function testPropertyCubes()
    {
    }

    /**
     * Test attribute "descrip"
     */
    public function testPropertyDescrip()
    {
    }

    /**
     * Test attribute "descrip2"
     */
    public function testPropertyDescrip2()
    {
    }

    /**
     * Test attribute "discamt"
     */
    public function testPropertyDiscamt()
    {
    }

    /**
     * Test attribute "discoverfl"
     */
    public function testPropertyDiscoverfl()
    {
    }

    /**
     * Test attribute "dsplprod"
     */
    public function testPropertyDsplprod()
    {
    }

    /**
     * Test attribute "extra_1"
     */
    public function testPropertyExtra1()
    {
    }

    /**
     * Test attribute "extra_2"
     */
    public function testPropertyExtra2()
    {
    }

    /**
     * Test attribute "icspecrecno"
     */
    public function testPropertyIcspecrecno()
    {
    }

    /**
     * Test attribute "keyindex"
     */
    public function testPropertyKeyindex()
    {
    }

    /**
     * Test attribute "lastprice"
     */
    public function testPropertyLastprice()
    {
    }

    /**
     * Test attribute "lookupnm"
     */
    public function testPropertyLookupnm()
    {
    }

    /**
     * Test attribute "marginamt"
     */
    public function testPropertyMarginamt()
    {
    }

    /**
     * Test attribute "netord"
     */
    public function testPropertyNetord()
    {
    }

    /**
     * Test attribute "netrecommend"
     */
    public function testPropertyNetrecommend()
    {
    }

    /**
     * Test attribute "notesfl"
     */
    public function testPropertyNotesfl()
    {
    }

    /**
     * Test attribute "oper2"
     */
    public function testPropertyOper2()
    {
    }

    /**
     * Test attribute "operinit"
     */
    public function testPropertyOperinit()
    {
    }

    /**
     * Test attribute "optionalwords"
     */
    public function testPropertyOptionalwords()
    {
    }

    /**
     * Test attribute "pdrecno"
     */
    public function testPropertyPdrecno()
    {
    }

    /**
     * Test attribute "pdsvfl"
     */
    public function testPropertyPdsvfl()
    {
    }

    /**
     * Test attribute "prccostper"
     */
    public function testPropertyPrccostper()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "priceoverfl"
     */
    public function testPropertyPriceoverfl()
    {
    }

    /**
     * Test attribute "prod"
     */
    public function testPropertyProd()
    {
    }

    /**
     * Test attribute "prodcat"
     */
    public function testPropertyProdcat()
    {
    }

    /**
     * Test attribute "prodcost"
     */
    public function testPropertyProdcost()
    {
    }

    /**
     * Test attribute "qtyavail"
     */
    public function testPropertyQtyavail()
    {
    }

    /**
     * Test attribute "qtybreakty"
     */
    public function testPropertyQtybreakty()
    {
    }

    /**
     * Test attribute "qtyord"
     */
    public function testPropertyQtyord()
    {
    }

    /**
     * Test attribute "qtyrecommend"
     */
    public function testPropertyQtyrecommend()
    {
    }

    /**
     * Test attribute "seasontype"
     */
    public function testPropertySeasontype()
    {
    }

    /**
     * Test attribute "seqno"
     */
    public function testPropertySeqno()
    {
    }

    /**
     * Test attribute "specconv"
     */
    public function testPropertySpecconv()
    {
    }

    /**
     * Test attribute "speccostty"
     */
    public function testPropertySpeccostty()
    {
    }

    /**
     * Test attribute "specsntype"
     */
    public function testPropertySpecsntype()
    {
    }

    /**
     * Test attribute "statmessage"
     */
    public function testPropertyStatmessage()
    {
    }

    /**
     * Test attribute "stkqtyord"
     */
    public function testPropertyStkqtyord()
    {
    }

    /**
     * Test attribute "stkqtyrecommend"
     */
    public function testPropertyStkqtyrecommend()
    {
    }

    /**
     * Test attribute "totalstkqty"
     */
    public function testPropertyTotalstkqty()
    {
    }

    /**
     * Test attribute "transdt"
     */
    public function testPropertyTransdt()
    {
    }

    /**
     * Test attribute "transrroc"
     */
    public function testPropertyTransrroc()
    {
    }

    /**
     * Test attribute "transtm"
     */
    public function testPropertyTranstm()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }

    /**
     * Test attribute "unitconv"
     */
    public function testPropertyUnitconv()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "whse"
     */
    public function testPropertyWhse()
    {
    }
}
