<?php
/**
 * TWtlineitemv2Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SX.e API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TWtlineitemv2Test Class Doc Comment
 *
 * @category    Class
 * @description TWtlineitemv2
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TWtlineitemv2Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TWtlineitemv2"
     */
    public function testTWtlineitemv2()
    {
    }

    /**
     * Test attribute "approvety"
     */
    public function testPropertyApprovety()
    {
    }

    /**
     * Test attribute "bono"
     */
    public function testPropertyBono()
    {
    }

    /**
     * Test attribute "duedt"
     */
    public function testPropertyDuedt()
    {
    }

    /**
     * Test attribute "lineno"
     */
    public function testPropertyLineno()
    {
    }

    /**
     * Test attribute "netamt"
     */
    public function testPropertyNetamt()
    {
    }

    /**
     * Test attribute "netord"
     */
    public function testPropertyNetord()
    {
    }

    /**
     * Test attribute "netrcv"
     */
    public function testPropertyNetrcv()
    {
    }

    /**
     * Test attribute "nonstockty"
     */
    public function testPropertyNonstockty()
    {
    }

    /**
     * Test attribute "ordertype"
     */
    public function testPropertyOrdertype()
    {
    }

    /**
     * Test attribute "orderaltno"
     */
    public function testPropertyOrderaltno()
    {
    }

    /**
     * Test attribute "tiedorder"
     */
    public function testPropertyTiedorder()
    {
    }

    /**
     * Test attribute "prodcost"
     */
    public function testPropertyProdcost()
    {
    }

    /**
     * Test attribute "proddesc"
     */
    public function testPropertyProddesc()
    {
    }

    /**
     * Test attribute "proddesc2"
     */
    public function testPropertyProddesc2()
    {
    }

    /**
     * Test attribute "prodinrcvfl"
     */
    public function testPropertyProdinrcvfl()
    {
    }

    /**
     * Test attribute "qtyord"
     */
    public function testPropertyQtyord()
    {
    }

    /**
     * Test attribute "qtyrcv"
     */
    public function testPropertyQtyrcv()
    {
    }

    /**
     * Test attribute "qtyship"
     */
    public function testPropertyQtyship()
    {
    }

    /**
     * Test attribute "shipprod"
     */
    public function testPropertyShipprod()
    {
    }

    /**
     * Test attribute "stkqtyord"
     */
    public function testPropertyStkqtyord()
    {
    }

    /**
     * Test attribute "stkqtyrcv"
     */
    public function testPropertyStkqtyrcv()
    {
    }

    /**
     * Test attribute "stkqtyship"
     */
    public function testPropertyStkqtyship()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }

    /**
     * Test attribute "unitconv"
     */
    public function testPropertyUnitconv()
    {
    }

    /**
     * Test attribute "sort_fld"
     */
    public function testPropertySortFld()
    {
    }

    /**
     * Test attribute "rcvunavailfl"
     */
    public function testPropertyRcvunavailfl()
    {
    }
}
